---
    - name: Failing if authorization is not properly configured
      fail:
        msg: "You did not set fame_user and fame_password in your configuration. This is required for fy_nl_ASR to work! If you do not have the credentials yet, contact h.vandenheuvel@let.ru.nl to request access."
      when: fame_user == "undefined" or fame_password == "undefined"

    - name: Installing webservice
      include_role:
        name: lamachine-python-install
      vars:
        package:
           github_user: "schemreier"
           github_repo: "fy-nl_ASR" #github repo is named differently than the python module (hyphen vs underscore)
           metadata:
              identifier: "fy_nl_ASR"

    - name: Link Python package installation in opt/
      become: "{{lm_become}}"
      become_user: root
      shell: |
        export DIR=$(python3 -c "import {{item}}; print({{item}}.__path__[0])")
        if [ ! -e "$DIR" ]; then
            echo "Unable to find dir"
            exit 2
        fi
        if [ -e "{{lm_prefix}}/opt/{{item}}" ]; then
          rm "{{lm_prefix}}/opt/{{item}}"
        fi
        ln -sf $DIR {{lm_prefix}}/opt/{{item}}
      with_items:
        - fy_nl_ASR
      environment: "{{lm_env}}"

    - name: Removing old resources (if present)
      file:
          path: "{{lm_prefix}}/opt/fame_resources"
          state: absent
      ignore_errors: yes #in case it isn't there in the first place

    - name: Creating directory for resources
      become: "{{lm_become}}"
      become_user: root
      file:
          path: "{{lm_prefix}}/opt/fame_resources"
          state: directory
          owner: "{{unix_user}}"
          group: "{{unix_group}}"
          mode: u+rwx,g+rwsx,a+rx

    - name: Downloading resources
      get_url:
        url: https://applejack.science.ru.nl/downloads/fame/fame/fame_resources.tar.gz
        url_username: "{{fame_user}}"
        url_password: "{{fame_password}}"
        dest: "{{lm_prefix}}/opt/fame_resources"

    - name: Unpacking resources
      unarchive:
        src: "{{lm_prefix}}/opt/fame_resources/fame_resources.tar.gz"
        dest: "{{lm_prefix}}/opt/fame_resources/"

    - name: Finalising resource installation
      shell: |
          #!/bin/bash
          rm -rf fame_resources.tar.gz
          mv resources/* .
          chown -R {{unix_user}}:{{unix_group}} .
          find . -type d | xargs chmod u+rw,g+rw,a+rx
          find . -type f | xargs chmod u+rw,g+rw,a+r
      args:
          chdir: "{{lm_prefix}}/opt/fame_resources"

    - name: "Install webserver configuration for fy_nl_ASR"
      become: "{{lm_become}}"
      become_user: root
      template:
        src: "nginx/fy_nl_ASR.conf"
        dest: "{{lm_prefix}}/etc/nginx/conf.d/fy_nl_ASR.conf"
        force: yes
        backup: yes
        owner: "{{unix_user}}"
      when: webservertype == "nginx"

    - name: "Install uwsgi configuration for fy_nl_ASR"
      become: "{{lm_become}}"
      become_user: root
      template:
        src: "uwsgi/fy_nl_ASR.ini"
        dest: "{{lm_prefix}}/etc/uwsgi-emperor/vassals/fy_nl_ASR.ini"
        force: yes
        backup: yes
        owner: "{{web_user}}"
        group: "{{web_group}}"

    - name: "Install clam configuration for fy_nl_ASR"
      become: "{{lm_become}}"
      become_user: root
      template:
        src: "clam/fy_nl_ASR.config.yml"
        dest: "{{lm_prefix}}/etc/fy_nl_ASR.config.yml"
        force: yes
        backup: yes
        owner: "{{unix_user}}"

    - name: Register webservice metadata
      include_role:
          name: lamachine-register
      vars:
          update: "{{item}}"
          metadata: #add entrypoint metadata to registry
              identifier: "{{item}}"
              entryPoints:
                - { "@type": "EntryPoint",  urlTemplate: "{{lm_base_url}}/{{item}}", interfaceType: "WUI", mediatorApplication: "#fy_nl_ASR" }
                - { "@type": "EntryPoint",  urlTemplate: "{{lm_base_url}}/{{item}}", interfaceType: "REST", specification: "{{lm_base_url}}/{{item}}/info",  mediatorApplication: "#fy_nl_ASR" }
      when: '"all" in services or item in services'
      with_items:
        - fy_nl_ASR


