---

 - name: "Installing R and generic 3rd party r packages via conda"
   command: "{{local_prefix}}/bin/conda install -mqy -p {{local_prefix}} r"
   when: localenv_type == "conda" and not prefer_global
 - name: "Making sure all conda packages are up to date"
   command: "{{local_prefix}}/bin/conda update -mqy -p {{local_prefix}} --all"
   when: localenv_type == "conda" and not prefer_global

 - name: "Installing R globally"
   block:
       - name: Install R globally (Debian/Ubuntu)
         become: yes
         become_user: root
         apt:
             name: r-recommended
             state: latest
         when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"
       - name: Install R globally (RedHat)
         become: yes
         become_user: root
         yum:
             name: R
             state: latest
         when: ansible_distribution == "RedHat" or ansible_distribution == "CentOS" or ansible_distribution == "Fedora"
       - name: Install R globally (Arch)
         become: yes
         become_user: root
         pacman:
             name: r
             state: latest
         when: ansible_distribution == "Arch"
   when: root and (prefer_global or localenv_type != "conda")
