---

    - name: Installing Python package for GLEM
      include_role:
        name: lamachine-python-install
      vars:
        package:
            github_user: "GreekPerspective"
            github_repo: "glem"

    - name: Register webservice
      include_role:
          name: lamachine-register
      vars:
        update: "glem"
        allow_failure: yes #in case the app is not installed
        package:
            pip: "glem"
        metadata: #add entrypoint metadata to registry
            identifier: "glem"
            producer: "{{ metadata_producer_clst }}"
            entryPoints:
              - { "@type": "EntryPoint",  urlTemplate: "{{lm_base_url}}/glem", interfaceType: "WUI" }
              - { "@type": "EntryPoint",  urlTemplate: "{{lm_base_url}}/glem", interfaceType: "REST", specification: "{{lm_base_url}}/glem/info" }

    - name: Installing web service
      include_role:
        name: lamachine-web-install
      vars:
        service:
          nginx: glem
          clam: glem
          uwsgi: glem

    - name: Link Python package installation in opt/
      include_role:
        name: lamachine-python-link
      with_items:
        - glem

    - name: Link Python package installation in opt/
      include_role:
        name: lamachine-python-link
      with_items:
        - webglem
