---
lm_prefix: "{% if locality == 'global' %}{{global_prefix}}{% else %}{{local_prefix}}{%endif%}"
lm_become: "{% if locality == 'global' and root %}yes{% else %}no{% endif %}"
lm_path: "{% if controller is defined %}{% if controller == 'internal' %}{{ source_path }}/LaMachine{% else %}{{ lamachine_path }}{% endif %}{% else %}{{ lamachine_path }}{% endif %}"
localenv:
     VIRTUAL_ENV: "{{local_prefix}}"
     PATH: "{{local_prefix}}/bin:{{ansible_env.PATH}}"
     LD_LIBRARY_PATH: "{{local_prefix}}/lib:{% if 'LD_LIBRARY_PATH' in ansible_env %}{{ansible_env.LD_LIBRARY_PATH}}{% else %}/usr/lib{% endif %}"
     CLANG_CXX_LIBRARY: "{% if ansible_distribution|lower == 'macosx' %}libc++{% endif %}" #needed for python bindings in lamachine-python-install
     MACOSX_DEPLOYMENT_TARGET: "{% if ansible_distribution|lower == 'macosx' %}{{ ansible_distribution_version }}{% endif %}"
globalenv:
     PATH: "{{global_prefix}}/bin:{{ansible_env.PATH}}"
     LD_LIBRARY_PATH: "{{global_prefix}}/lib:{% if 'LD_LIBRARY_PATH' in ansible_env %}{{ansible_env.LD_LIBRARY_PATH}}{% else %}/usr/lib{% endif %}"
     CLANG_CXX_LIBRARY: "{% if ansible_distribution|lower == 'macosx' %}libc++{% endif %}" #needed for python bindings in lamachine-python-install
     MACOSX_DEPLOYMENT_TARGET: "{% if ansible_distribution|lower == 'macosx' %}{{ ansible_distribution_version }}{% endif %}"
lm_env: "{% if locality == 'global'  %}{{globalenv}}{% else %}{{localenv}}{% endif %}"



