---
- when: "'exclude_when' not in package or not package.exclude_when"
  block:
    - name: "{% if 'github_repo' in package %}{{package.github_repo}}{% else %}(NOT APPLICABLE){% endif %} - Installing latest version from github (development)"
      block:
        - name: "{{package.github_repo}} - Git clone/pull latest {% if 'git_branch' in package %}{{ package.git_branch }}{% else %}master{% endif %}" #we always do this, even if we're not using the source for installation (we still need to check for codemeta.json)
          git:
            repo: "https://github.com/{{package.github_user}}/{{package.github_repo}}"
            dest: "{{ source_path }}/{{ package.github_repo }}"
            version: "{% if 'git_branch' in package %}{{ package.git_branch }}{% else %}master{% endif %}"
            recursive: yes
            update: yes
          environment: "{{lm_env}}"
          when: '"github_user" in package and package.github_user != "" and "github_repo" in package and package.github_repo != ""'

        - name: "{{package.github_repo}} - Installing python package (development)"
          become: "{{lm_become}}"
          become_user: root
          shell: "python3 {% if 'setup' in package %}{{package.setup}}{% else %}setup.py{% endif %} install"
          args:
            chdir: "{{ source_path }}/{{package.github_repo}}{% if 'setupdir' in package %}/{{ package.setupdir }}{% endif %}"
          environment: "{{lm_env}}"
          when: '"github_user" in package and package.github_user != "" and "github_repo" in package and package.github_repo != "" and (version == "development" or ("pip" not in package or package.pip == ""))'


    - name: "{% if 'pip' in package %}{{package.pip}}{% else %}(NOT APPLICABLE){% endif %} - Installing latest release from the Python Package Index (stable)"
      become: "{{lm_become}}"
      become_user: root
      pip:
           name: "{{package.pip}}"
           state: "{% if 'state' in package %}{{package.state}}{% else %}latest{% endif %}"
           executable: "{% if locality == 'local' %}{{ local_prefix }}/bin/pip{% else %}{{pip.stdout}}{% endif %}"
      environment: "{{lm_env}}"
      when: (version == "stable" or (version == "development" and ("github_user" not in package or package.github_user == ""))) and localenv_type != "conda" and "pip" in package and package.pip != ""

    - name: "{% if 'github_repo' in package %}{{package.github_repo}}{% else %}(NOT APPLICABLE){% endif %} - Checking whether codemeta.json is provided"
      stat:
        path: "{{ source_path }}/{{package.github_repo}}/codemeta.json"
      register: have_codemeta
      changed_when: False
      when: "'github_repo' in package"


    - name: Register software metadata
      include_role:
          name: lamachine-register
      vars:
          codemeta: "{% if 'github_repo' in package and have_codemeta.stat.exists %}{{ source_path }}/{{package.github_repo}}/codemeta.json{% endif %}"
          metadata_defaults:
             identifier: "{% if 'pip' in package %}{{package.pip|lower}}{% else %}{{ package.github_repo|lower }}{% endif %}"
             name: "{% if 'pip' in package %}{{package.pip}}{% else %}{{ package.github_repo }}{% endif %}"
             codeRepository: "{% if 'github_repo' in package %}https://github.com/{{package.github_user}}/{{package.github_repo}}{% endif %}"
      when: do_registration



