{% if clam_include %}
include: "{{clam_include}}"
{% endif %}
port: 8805
urlprefix: "alpino"
root: "{{www_data_path}}/alpino.clam/"
bindir: "{{lm_prefix}}/bin/"
{% if "switchboard" in remote_services and remote_services.switchboard %}
switchboard_forward_url: "{{remote_services.switchboard}}/#/alpino/$BACKLINK/$MIMETYPE/nld"
{% endif %}
