---

 - name: "Installing generic 3rd party Python Packages via conda"
   conda:
       name: "{{item}}"
       state: latest
       executable: "/home/{{unix_user}}/miniconda/bin/conda"
       extra_args: "-n {{env_name}}"
   with_items:
       - beautifulsoup4
       - flask
       - ipython
       - jupyter
       - lxml
       - matplotlib
       - nbconvert
       - nltk
       - numpy
       - pandas
       - pycrypto
       - pylint
       - pymongo
       - pymysql
       - scikit-learn
       - scipy
       - spacy
       - sphinx
       - tensorflow
       - word2vec
       - xlsxwriter
       - yaml
   when: localenv_type == "conda"


 - name: "Installing {{item}} via pip"
   pip:
       name: "{{item}}"
       state: latest
       virtualenv: "{{ local_prefix }}"
   with_items:
       - beautifulsoup4
       - flask
       - ipython
       - jupyter
       - lxml
       - matplotlib
       - nbconvert
       - nltk
       - numpy
       - pandas
       - pycrypto
       - pylint
       - pymongo
       - pymysql
       - scikit-learn
       - scipy
       - spacy
       - sphinx
       - tensorflow
       - word2vec
       - xlsxwriter
       - yaml
   when: localenv_type == "virtualenv"
