language: python

python:
    - 3.3
    - 3.4
sudo: required
before-install:
    - sudo apt-get update
install: 
    - bash virtualenv-bootstrap.sh  #cause of travis' setup, we will already be in a virtualenv and reuse it
script:
    - export LD_LIBRARY_PATH="$VIRTUAL_ENV/lib/:$LD_LIBRARY_PATH" #cause of travis' setup, we will already be in a virtualenv and reuse it, little hack to get LD_LIBRARY_PATH right
    - which ucto
    - which frog
    - which timbl
    - which mbt
    - which wopr
    - which foliavalidator
    - python -c "import pynlpl"
    - python -c "import timbl"
    - python -c "import ucto"
    - python -c "import frog"
    - python -c "import colibricore"
