language: generic

matrix:
    include:
        - os: linux
          dist: trusty
          sudo: required
          language: generic
          env:
            - LM_NAME=travis-stable-conda FLAVOUR=local VERSION=stable LOCALENV_TYPE=conda EXTRAOPT=""
        - os: linux
          dist: trusty
          sudo: required
          language: generic
          env:
            - LM_NAME=travis-stable-venv FLAVOUR=local VERSION=stable LOCALENV_TYPE=virtualenv EXTRAOPT=""
        - os: linux
          dist: trusty
          sudo: required
          language: generic
          env:
            - LM_NAME=travis-stable-conda-noroot FLAVOUR=local VERSION=stable LOCALENV_TYPE=conda EXTRAOPT="--noroot"
        - os: linux
          dist: trusty
          sudo: required
          language: generic
          env:
            - LM_NAME=travis-stable-venv-noroot FLAVOUR=local VERSION=stable LOCALENV_TYPE=virtualenv EXTRAOPT="--noroot"
        - os: linux
          dist: trusty
          sudo: required
          language: generic
          env:
            - LM_NAME=travis-dev-conda FLAVOUR=local VERSION=development LOCALENV_TYPE=conda EXTRAOPT=""
        - os: linux
          dist: trusty
          sudo: required
          language: generic
          env:
            - LM_NAME=travis-dev-venv FLAVOUR=local VERSION=development LOCALENV_TYPE=virtualenv EXTRAOPT=""
        - os: osx
          language: generic
          env:
            - LM_NAME=travis-stable-conda FLAVOUR=local VERSION=stable LOCALENV_TYPE=conda EXTRAOPT=""
        - os: osx
          language: generic
          env:
            - LM_NAME=travis-dev-conda FLAVOUR=local VERSION=development LOCALENV_TYPE=conda EXTRAOPT=""
notifications:
  irc:
    channels:
      - "irc.uvt.nl#gitlama"
    template:
      - "%{repository_slug}#%{build_number} %{message} --> %{build_url}"
    skip_join: true

install:
    - if [[ $TRAVIS_OS_NAME == "linux" ]]; then sudo /etc/init.d/postgresql stop; sudo apt remove postgresql-9.3 postgresql-9.4 postgresql-9.5 postgresql-9.6 postgresql-contrib-9.3 postgresql-contrib-9.4 postgresql-contrib-9.5 postgresql-contrib-9.6 ; fi #this is in the way and breaks apt updates for some reason
    - if [[ $TRAVIS_OS_NAME == "linux" ]] && [[ "$EXTRAOPT" == "--noroot" ]]; then sudo apt-get install pkg-config git-core make gcc g++ autoconf automake autoconf-archive libtool autotools-dev libicu-dev libxml2-dev libxslt1-dev libbz2-dev zlib1g-dev libtar-dev libaspell-dev libhunspell-dev libboost-all-dev libgnutls-dev python3 python-virtualenv python3-dev libexttextcat-dev; fi #install global dependencies manually because we pretend not to have root
    - if [[ $TRAVIS_OS_NAME == "osx" ]]; then sudo easy_install pip; fi #prevent bootstrap from querying this interactively
script:
    - bash bootstrap.sh --name $LM_NAME --flavour $FLAVOUR --version $VERSION --env $LOCALENV_TYPE --noninteractive --notshared --extra "nosysupdate=true" $EXTRAOPT --verbose

