language: python

matrix:
    include:
        - os: linux
          dist: trusty
          sudo: required
          python: 3.4
        - os: osx
          osx_image: xcode8.2
          env: TOXENV=py34

install: 
    - travis_wait 60 bash virtualenv-bootstrap.sh noninteractive #cause of travis' setup, we will already be in a virtualenv and reuse it
script:
    - LD_LIBRARY_PATH="$VIRTUAL_ENV/lib/:$LD_LIBRARY_PATH" ./test.sh #cause of travis' setup, we will already be in a virtualenv and reuse it, little hack to get LD_LIBRARY_PATH right
