---
#################################################################################################################
#                                   LaMachine Installation Manifest
#
# INSTRUCTIONS: Comment or remove categories/roles you do not want to install, dependencies will be automatically
# resolved even when not explicitly mentioned)
#
# NOTE: ensure that all enabled roles are lined up with the same amount of spaces!
#       (all hyphens must be vertically on the same column!)
#       (don't use tabs)
#
################################################################################################################
- hosts: all
  roles:
      - lamachine-core                   ## The LaMachine core ##
                                              #you always need this or nothing works; already includes Python 3
      - languagemachines-basic           ## Generic & Dutch NLP tools written in C++ ##
                                              #by the Language Machines Research group,
                                              #Centre for Language and Speech Technology, Radboud University Nijmegen
                                              #(provides: timbl, frog, ucto, folia, mbt, wopr, Colibri Core)
      - python-core                      ## Core 3rd party scientific python packages ###
                                              #(provides: numpy, scipy, pandas, matplotlib, scikit-learn, nltk, and more)
      - languagemachines-python          ## Python-based NLP tools and libraries and web applications/services ##
                                              #by the Language Machines Research group,
                                              #Centre for Language and Speech Technology, Radboud University Nijmegen
                                             #(this includes pynlpl, pynlpl.formats.folia, CLAM, foliadocserve, FLAT, babelente)
      - languagemachines-python-bindings ## Provides Python bindings to C++ software ##
                                             #(provides python-ucto, python-frog, python-timbl, colibricore)
      - java-core                        ## Java 8, Maven ##
      - r-core                           ## R with core R packages ##
     # - piccl                            ## PICCL: Workflows for Post-OCR correction and normalisation and pseudo-modernisation of historical text. ##
                                             # [2.2GB! - not supported on Mac OS X]
                                             # (provides TICCL-Tools)
     # - alpino                           ## ALPINO: Dependency parser for Dutch ##
                                             # by Groningen University
                                             # [1.6GB! - only supported on Debian/Ubuntu for now]
     # - tscan                            ## T-Scan: Software for feature extraction for readability prediction ##
                                             # by Utrecht University, Tilburg University & Radboud University
                                             # [requires Alpino, so only supported on Debian/Ubuntu]
     # - gecco                            ## Generic software for context-aware spelling correction ##
                                             # Centre for Language and Speech Technology, Radboud University Nijmegen
                                             # [Not supported on Mac OS X]
     # - valkuil                          ## A Dutch Spelling corrector ##
                                             # Centre for Language and Speech Technology, Radboud University Nijmegen
                                             # [1.2GB! - Not supported on Mac OS X, requires at least 32GB RAM]
     # - tensorflow                       ## Tensorflow Deep Learning Library for Python (by Google) ##
                                             #(>250MB)
     # - spacy                            ## spaCy is a library for advanced Natural Language Processing in Python and Cython ##
                                             #(>500MB)

# NOTE: ensure that all enabled roles are lined up with the same amount of spaces!
#       (all hyphens must be vertically on the same column!)
#       (don't use tabs)






