---
    - name: "Installing PyTorch"
      include_role:
          name: lamachine-python-install
      with_items:
          - { pip: torch }
          - { pip: torchvision }
      loop_control:
           loop_var: package

    - name: "Installing Flair (Python >=3.6 only)"
      include_role:
          name: lamachine-python-install
      vars:
        package:
          pip: flair
      when: python_version.stdout >= "3.6"
