---
    - name: "Installing PyTorch"
      include_role:
          name: lamachine-python-install
      with_items:
          - { pip: torch }
          - { pip: torchvision }
          - { pip: flair }
      loop_control:
           loop_var: package

