---

  - name: Check for unsupported OS for Kaldi
    debug:
      msg: "Kaldi is not supported on Mac OS X"
    when: ansible_distribution|lower == "macosx"

  - name: Installing global dependencies for Kaldi and alex-asr
    include_role:
      name: lamachine-package-install
    with_items:
      - { debian: libatlas-base-dev, redhat: atlas-devel }
      - { debian: gfortran, redhat: libgfortran, arch: gcc-fortran }
    loop_control:
        loop_var: package
    when: root

  - name: "Checking out Kaldi"
    git:
      repo: "{{kaldi_source}}"
      dest: "{{lm_prefix}}/opt/kaldi"
      version: "{{kaldi_branch}}"
      force: yes

  - name: Patch OpenFST makefile so that we can link with it statically (needed for Alex-ASR)
    shell: sed -i "s/--enable-far --enable-ngram-fsts/--enable-far --with-pic --enable-ngram-fsts/" Makefile
    args:
       chdir: "{{lm_prefix}}/opt/kaldi/tools"

  - name: Compiling kaldi/tools
    shell: make -j $(nproc)
    args :
      chdir: "{{lm_prefix}}/opt/kaldi/tools"
    environment:
      KALDI_ROOT: "{{lm_prefix}}/opt/kaldi"
    ignore_errors: yes #obviously not a good idea

  - name: Configuring kaldi/src
    shell: "./configure {{kaldi_configure_options}}"
    args:
      chdir: "{{lm_prefix}}/opt/kaldi/src"

  - name: Compiling kaldi/src
    shell: make -j $(nproc)
    args:
      chdir: "{{lm_prefix}}/opt/kaldi/src"
    environment:
      KALDI_ROOT: "{{lm_prefix}}/opt/kaldi"

  - name: Testing kaldi
    shell: make test
    args:
      chdir: "{{lm_prefix}}/opt/kaldi/src"
    environment:
      KALDI_ROOT: "{{lm_prefix}}/opt/kaldi"
    ignore_errors: "{{ kaldi_test_ignore_errors }}"

  - name: "Adding activation script for Kaldi"
    become: "{{lm_become}}"
    become_user: root
    copy:
      dest: "{{lm_prefix}}/bin/activate.d/kaldi.sh"
      content: |
        export KALDI_ROOT={{lm_prefix}}/opt/kaldi
      mode: u+rwx,a+rx

  - name: "Kaldi - Get latest commit hash"
    shell: "git describe --tags || git rev-parse HEAD"
    args:
      chdir: "{{ lm_prefix }}/opt/kaldi"
    register: latest_commit
    changed_when: False

  - name: Register Kaldi
    include_role:
       name: lamachine-register
    vars:
       metadata:
         identifier: kaldi
         name: Kaldi
         version: "{{ latest_commit.stdout }}"
         author: (multiple)
         url: "http://kaldi-asr.org/"
         codeRepository: "https://github.com/kaldi-asr/kaldi"
         license: Apache
         description: "Automatic Speech Recognition Toolkit"
         programmingLanguage: "C++"
         interfaceType: CLI
         keywords: [ "speech recognition", "asr", "cuda" ]

