---

  - name: Check for unsupported OS for Kaldi
    debug:
      msg: "Kaldi is not supported on Mac OS X"
    when: ansible_distribution|lower == "macosx"

  - name: Installing global dependencies for Kaldi and alex-asr
    include_role:
      name: lamachine-package-install
    with_items:
      - { debian: libatlas-base-dev, redhat: atlas-devel }
      - { debian: gfortran, redhat: libgfortran, arch: gcc-fortran }
    loop_control:
        loop_var: package
    when: root

  - name: "Checking out Kaldi"
    git:
      repo: "{{kaldi_source}}"
      dest: "{{lm_prefix}}/opt/kaldi"
      version: "{{kaldi_branch}}"
      force: yes

  - name: Compiling kaldi/tools
    shell: make -j $(nproc)
    args :
      chdir: "{{lm_prefix}}/opt/kaldi/tools"
    environment:
      KALDI_ROOT: "{{lm_prefix}}/opt/kaldi"
    ignore_errors: yes #obviously not a good idea

  - name: Configuring kaldi/src
    shell: ./configure
    args:
      chdir: "{{lm_prefix}}/opt/kaldi/src"

  - name: Compiling kaldi/src
    shell: make -j $(nproc)
    args:
      chdir: "{{lm_prefix}}/opt/kaldi/src"
    environment:
      KALDI_ROOT: "{{lm_prefix}}/opt/kaldi"
    ignore_errors: yes #obviously not a good idea

  - name: "Adding activation script for Kaldi"
    become: "{{lm_become}}"
    become_user: root
    copy:
      dest: "{{lm_prefix}}/bin/activate.d/kaldi.sh"
      content: |
        export KALDI_ROOT={{lm_prefix}}/opt/kaldi
      mode: u+rwx,a+rx

  - name: Register Kaldi
    include_role:
       name: lamachine-register
    vars:
       metadata:
         name: Kaldi
         author: (multiple)
         homepage: "http://kaldi-asr.org/"
         license: Apache
         summary: "Automatic Speech Recognition Toolkit"

  - name: Installing Alex-ASR
    include_role:
      name: lamachine-python-install
    vars:
      package:
         github_user: "UFAL-DSG"
         github_repo: "alex-asr"
         #pip: "alex_asr"
