---

    - name: Obtaining kaldi_nl
      git:
        repo: "https://github.com/opensource-spraakherkenning-nl/Kaldi_NL/"
        dest: "{{ lm_prefix }}/opt/kaldi_nl"
        update: yes
        recursive: yes
        accept_hostkey: yes

    - name: Setting up kaldi_nl
      command: "./configure.sh oralhistory"
      args:
        chdir: "{{ lm_prefix }}/opt/kaldi_nl"
      environment: "{{lm_env}}"
