---

    - name: Installing g2pservice python package
      include_role:
        name: lamachine-python-install
      vars:
        package:
          name: "g2pservice"
          github_user: "opensource-spraakherkenning-nl"
          github_repo: g2pservice

    - name: Register webservice
      include_role:
          name: lamachine-register
      vars:
        update: "g2pservice"
        package:
           pip: "g2pservice"
        allow_failure: yes #in case the app is not installed
        metadata: #add entrypoint metadata to registry
            identifier: "g2pservice"
            entryPoints:
              - { "@type": "EntryPoint",  urlTemplate: "{{lm_base_url}}/g2pservice", interfaceType: "WUI" }
              - { "@type": "EntryPoint",  urlTemplate: "{{lm_base_url}}/g2pservice", interfaceType: "REST", specification: "{{lm_base_url}}/g2pservice/info" }

    - name: Installing web service
      include_role:
        name: lamachine-web-install
      vars:
        service:
          nginx: g2pservice
          clam: g2pservice
          uwsgi: g2pservice

    - name: Link Python package installation in opt/
      include_role:
        name: lamachine-python-link
      with_items:
        - g2pservice
