---


    - name: Installing Python bindings
      include_role:
        name: lamachine-python-install
      with_items:
          - { github_user: "proycon", github_repo: "python-timbl", pip: "python3-timbl", conda: "", setup: "setup3.py" }
          - { github_user: "proycon", github_repo: "python-ucto", pip: "python-ucto", conda: "" }
          - { github_user: "proycon", github_repo: "python-frog", pip: "python-frog", conda: "" }
      loop_control:
          loop_var: package


    - name: Triggering manual mode for Colibri Core #otherwise setup.py will attempt to recompile c++ sources (and fail on a permission issue)
      file:
        path: "{{source_path}}/colibri-core/manual"
        state: touch
      changed_when: False

    - name: Installing Colibri Core Python Binding
      include_role:
        name: lamachine-python-install
      vars:
        package:
          github_user: proycon
          github_repo: colibri-core #always installed from source, will reuse same sourcedir as C++ lib
        metadata:
          identifier: colibricore_python

    - name: Testing Python bindings
      include_role:
          name: lamachine-run
      vars:
          command: "python3 -c 'import {{ item }}'"
      with_items:
          - ucto
          - timbl
          - frog
          - colibricore
      register: test
      changed_when: test.rc != 0

