---

    - name: Installing boost for anaconda
      command: "{{local_prefix}}/bin/conda install -mqy -p {{local_prefix}} -c anaconda boost"
      when: localenv_type == "conda" and not prefer_global

    - name: Installing Python bindings
      include_role:
        name: python-install
      vars:
        github_user: "{{item.github_user}}"
        github_repo: "{{item.github_repo}}"
        pip_package: "{{item.pip_package}}"
        conda_package: "{{item.conda_package}}"
      with_items:
          - { github_user: "proycon", github_repo: "python-timbl", pip_package: "python3-timbl", conda_package: ""}
          - { github_user: "proycon", github_repo: "python-ucto", pip_package: "python-ucto", conda_package: ""}
          - { github_user: "proycon", github_repo: "python-frog", pip_package: "python-frog", conda_package: ""}

    - name: Installing Colibri Core Python Binding
      include_role:
          name: lamachine_run
      vars:
          command: "python setup.py install --prefix={{local_prefix}}"
          chdir: "{{source_path}}/colibri-core" #always installed from source

    - block:
        - name: Testing Python bindings
          include_role:
              name: lamachine_run
          vars:
              command: "python -c 'import {{ item }}'"
          with_items:
              - ucto
              - timbl
              - frog
              - colibricore
          register: test
          changed_when: test.rc != 0
      rescue:
         - name: "Package list at time of failure"
           shell: "{{local_prefix}}/bin/conda -p {{local_prefix}} list"
           when: localenv_type == "conda" and not prefer_global

