---
    - name: Preparing conda for Python bindings
      command: "{{local_prefix}}/conda install -mqy -p {{local_prefix}} -c meznom boost-python"
      when: localenv_type == "conda" and not prefer_global

    - name: Installing Python bindings
      include_role:
        name: python-install
      vars:
        github_user: "{{item.github_user}}"
        github_repo: "{{item.github_repo}}"
        pip_package: "{{item.pip_package}}"
        conda_package: "{{item.conda_package}}"
        conda_channel: "{{item.conda_channel}}"
      with_items:
          - { github_user: "proycon", github_repo: "python-timbl", pip_package: "python3-timbl", conda_package: "", conda_channel:"" }
          - { github_user: "proycon", github_repo: "python-ucto", pip_package: "python-ucto", conda_package: "", conda_channel:"" }
          - { github_user: "proycon", github_repo: "python-frog", pip_package: "python-frog", conda_package: "", conda_channel:"" }
          - { github_user: "proycon", github_repo: "colibri-core", pip_package: "colibricore", conda_package: "", conda_channel:"" }
