---
    - name: Failing if authorization is not properly configured
      fail:
        msg: "You did not set fame_user and fame_password in your configuration. This is required for fame_align to work! If you do not have the credentials yet, contact h.vandenheuvel@let.ru.nl to request access."
      when: fame_user == "undefined" or fame_password == "undefined"

    - name: Install CLAM #so we don't need to rely on languagemachines-basic nor python-core
      include_role:
        name: lamachine-python-install
      with_items:
          - { pip: "flask" }
          - { pip: "lxml" }
          - { pip: "requests" }
          - { pip: "requests_oauthlib" }
          - { pip: "requests_toolbelt" }
          - { pip: "pycrypto" }
          - { pip: "certifi" }
          - { pip: "pyyaml" }
          - { github_user: "proycon", github_repo: "clam", pip: "clam" }
      loop_control:
           loop_var: package

    - name: Installing webservice
      include_role:
        name: lamachine-python-install
      vars:
        package:
           github_user: "schemreier"
           github_repo: "frisianalign" #github repo is named differently than the python module
           metadata:
              identifier: "fame_align"

    - name: Link Python package installation in opt/
      become: "{{lm_become}}"
      become_user: root
      shell: |
        export DIR=$(python3 -c "import {{item}}; print({{item}}.__path__[0])")
        if [ ! -e "$DIR" ]; then
            echo "Unable to find dir"
            exit 2
        fi
        if [ -e "{{lm_prefix}}/opt/{{item}}" ]; then
          rm "{{lm_prefix}}/opt/{{item}}"
        fi
        ln -sf $DIR {{lm_prefix}}/opt/{{item}}
      with_items:
        - clam
        - fame_align
      environment: "{{lm_env}}"

    - name: Removing old resources (if present)
      file:
          path: "{{lm_prefix}}/opt/fame_align_resources"
          state: absent
      ignore_errors: yes #in case it isn't there in the first place

    - name: Creating directory for resources
      become: "{{lm_become}}"
      become_user: root
      file:
          path: "{{lm_prefix}}/opt/fame_align_resources"
          state: directory
          owner: "{{unix_user}}"
          group: "{{unix_group}}"
          mode: u+rwx,g+rwsx,a+rx

    - name: Downloading resources
      get_url:
        url: https://applejack.science.ru.nl/downloads/fame/fame_align/fame_align_resources.tar.gz
        url_username: "{{fame_user}}"
        url_password: "{{fame_password}}"
        dest: "{{lm_prefix}}/opt/fame_align_resources/fame_align_resources.tar.gz"
        tmp_dest: "{{lm_prefix}}/opt/fame_align_resources"


    - name: Finalising resource installation
      shell: |
          #!/bin/bash
          tar xzf fame_align_resources.tar.gz
          rm -rf fame_align_resources.tar.gz
          mv resources/* .
          chown -R {{unix_user}}:{{unix_group}} .
          find . -type d | xargs chmod u+rw,g+rw,a+rx
          find . -type f | xargs chmod u+rw,g+rw,a+r
      args:
          chdir: "{{lm_prefix}}/opt/fame_align_resources"

    - name: "Install webserver configuration for fame_align"
      become: "{{lm_become}}"
      become_user: root
      template:
        src: "nginx/fame_align.conf"
        dest: "{{lm_prefix}}/etc/nginx/conf.d/fame_align.conf"
        force: yes
        backup: yes
        owner: "{{unix_user}}"
      when: webservertype == "nginx"

    - name: "Install uwsgi configuration for fame_align"
      become: "{{lm_become}}"
      become_user: root
      template:
        src: "uwsgi/fame_align.ini"
        dest: "{{lm_prefix}}/etc/uwsgi-emperor/vassals/fame_align.ini"
        force: yes
        backup: yes
        owner: "{{web_user}}"
        group: "{{web_group}}"

    - name: "Install clam configuration for fame_align"
      become: "{{lm_become}}"
      become_user: root
      template:
        src: "clam/fame_align.config.yml"
        dest: "{{lm_prefix}}/etc/fame_align.config.yml"
        force: yes
        backup: yes
        owner: "{{unix_user}}"

    - name: Register webservice metadata
      include_role:
          name: lamachine-register
      vars:
          update: "{{item}}"
          metadata: #add entrypoint metadata to registry
              identifier: "{{item}}"
              entryPoints:
                - { "@type": "EntryPoint",  urlTemplate: "{{lm_base_url}}/{{item}}", interfaceType: "WUI", mediatorApplication: "#fame_align" }
                - { "@type": "EntryPoint",  urlTemplate: "{{lm_base_url}}/{{item}}", interfaceType: "REST", specification: "{{lm_base_url}}/{{item}}/info",  mediatorApplication: "#fame_aligh" }
      when: '"all" in services or item in services'
      with_items:
        - fame_align


