---
    - name: Installing extra utilities (python)
      include_role:
        name: lamachine-python-install
      with_items:
          - { pip: "tldr" } #an alternative for 'man'
          - { pip: "glances" } #an alternative for 'top'
          - { pip: "csvkit" }
      loop_control:
          loop_var: package

    - name: Installing extra utilities (apt)
      become: true
      become_user: root
      apt:
        name: [ jq, ack, xmlstarlet, gnuplot, graphviz ]
        state: present
        update_cache: yes
        cache_valid_time: 900
      when: (ansible_distribution|lower == "ubuntu" or ansible_distribution|lower == "debian" or ansible_distribution|lower == "linux mint") and root
      ignore_errors: yes #allowed to fail if package is missing (older distros)

    - name: Installing extra utilities (arch)
      become: true
      become_user: root
      pacman:
        name: [ jq, bat, ack, xmlstarlet, gnuplot, graphviz ]
        state: installed
      when: (ansible_distribution|lower == "archlinux" or ansible_distribution|lower == "manjaro") and root

    - name: Installing extra utilities (yum)
      become: true
      become_user: root
      yum:
        name: [ jq, ack, xmlstarlet, gnuplot, graphviz ]
        state: installed
        update_cache: "{% if nosysupdate is not defined or nosysupdate == 0 %}yes{% else %}no{% endif %}"
      when: (ansible_distribution|lower == 'redhat' or ansible_distribution|lower == 'centos' or ansible_distribution|lower == 'fedora') and root
      ignore_errors: yes #allowed to fail if package is missing (older distros)

    - name: Installing extra utilities (macOS/homebrew)
      homebrew:
        name: [ jq, bat, ack, xmlstarlet, gnuplot, feedgnuplot, graphviz ]
        state: present
      when: ansible_distribution|lower == "macosx"
