{% if clam_include %}
include: "{{clam_include}}"
{% endif %}
port: 8806
urlprefix: "piccl"
root: "{{www_data_path}}/piccl.clam/"
piccldir: "{{lm_prefix}}/opt/PICCL"
piccldataroot: "{{lm_prefix}}/opt/PICCL"
