{% if clam_include %}
include: "{{clam_include}}"
{% endif %}
port: 8806
urlprefix: "piccl"
root: "{{www_data_path}}/piccl.clam/"
piccldir: "{{lm_prefix}}/opt/PICCL"
piccldataroot: "{{lm_prefix}}/opt/PICCL"
autosearch_forward_url: "https://portal.clarin.inl.nl/autocorp/upload/?format=piccl&file=$BACKLINK"
switchboard_forward_url: "https://switchboard.clarin.eu/#/piccl/$BACKLINK/$MIMETYPE"
