
- when: "'exclude_when' not in package or not package.exclude_when"
  block:
    - name: "{{package.repo}} - Check if repository exists"
      stat:
        path: "{{ source_path }}/{{package.repo}}"
      register: repo_path

    - name: "{{package.repo}} - Git clone"
      shell: "git clone {% if 'giturl' in package %}{{package.giturl}}{%else%}https://github.com/{{package.user}}/{{package.repo}}{% endif %}"
      args:
        chdir: "{{ source_path }}"
      when: not repo_path.stat.exists

    - when: version == "stable" and ("noreleases" not in package or not package.noreleases)
      block:
        - name: "{{package.repo}} - Get new git tags from remote"
          shell: "git fetch --tags"
          args:
            chdir: "{{ source_path }}/{{package.repo}}"
          changed_when: False

        - name: "{{package.repo}} - Get latest version tag"
          shell: "git tag -l | grep '^v' | sort -t. -k 1.2,1n -k 2,2n -k 3,3n -k 4,4n | tail -n 1 | tee .latest-release.lamachine"
          args:
            chdir: "{{ source_path }}/{{package.repo}}"
          register: latest_tag
          changed_when: False

        - name: "{{package.repo}} - Checkout latest stable version {{latest_tag.stdout}}"
          shell: "git checkout {{latest_tag.stdout}}"
          args:
            chdir: "{{ source_path }}/{{package.repo}}"
          register: gitcheckout
          changed_when: '"Switched to branch" in gitcheckout.stdout'

        - name: "{{package.repo}} - Register (stable)"
          include_role:
             name: lamachine-register
          vars:
             register:
               name: "{% if 'name' in package %}{{package.name}}{% else %}{{package.repo}}{% endif %}"
               author: "{% if 'author' in package %}{{package.author}}{% else %}{{package.user}}{% endif %}"
               homepage: "{% if 'homepage' in package %}{{package.homepage}}{% else %}{% if 'giturl' in package %}{{package.giturl}}{%else%}https://github.com/{{package.user}}/{{package.repo}}{% endif %}{% endif %}"
               version: "{{ latest_tag.stdout }}"
             package: "{% package|combine(register) %}"
          when: '"register" in package and package.register'

    - when: version == "development" or (version == "stable" and ("noreleases" in package and package.noreleases))
      block:
        - name: "{{package.repo}} - Checkout latest master version of (development)"
          shell: "git checkout master && git pull"
          args:
            chdir: "{{ source_path }}/{{package.repo}}"
          register: gitcheckout
          changed_when: '("Switched to branch" in gitcheckout.stdout) or ("files changed" in gitcheckout.stdout)'

        - name: "{{package.repo}} - Get latest commit hash"
          shell: "git rev-parse HEAD"
          args:
            chdir: "{{ source_path }}/{{package.repo}}"
          register: latest_commit
          changed_when: False

        - name: "{{package.repo}} - Register (unreleased)"
          include_role:
             name: lamachine-register
          vars:
             register:
               name: "{% if 'name' in package %}{{package.name}}{% else %}{{package.repo}}{% endif %}"
               author: "{% if 'author' in package %}{{package.author}}{% else %}{{package.user}}{% endif %}"
               homepage: "{% if 'homepage' in package %}{{package.homepage}}{% else %}{% if 'giturl' in package %}{{package.giturl}}{%else%}https://github.com/{{package.user}}/{{package.repo}}{% endif %}{% endif %}"
               version: "{{ latest_tag.stdout }}"
             package: "{% package|combine(register) %}"

    - name: "{{package.repo}} - Checkout custom version: {{customversion[package.repo]}}"
      shell: "git checkout {{customversion[package.repo]}} && git pull"
      args:
        chdir: "{{ source_path }}/{{package.repo}}"
      changed_when: '("Switched to branch" in gitcheckout.stdout) or ("files changed" in gitcheckout.stdout)'
      when: version == "custom"

