---

  - name: Installing Julia for macOS
    homebrew_cask:
      name: julia
      state: present
    when: ansible_distribution|lower == "macosx"

  - when: ansible_distribution|lower != "macosx"
    block:
      - name: Download Julia
        get_url:
          url: https://julialang-s3.julialang.org/bin/linux/x64/1.5/julia-1.5.1-linux-x86_64.tar.gz
          dest: "{{ source_path }}/julia.tar.gz"

      - name: Extracting/Installing Julia
        shell: |
          tar -xvzf julia.tar.gz --strip 1 -C {{lm_prefix}}
          rm {{lm_prefix}}/LICENSE.md #not the right place for it
          rm {{source_path}}/julia.tar.gz
        args:
          chdir: "{{ source_path }}"



