---
    - name: "Installing Spacy"
      include_role:
          name: lamachine-python-install
      with_items:
          - { pip: spacy }
          - { pip: spacy2folia }
      loop_control:
           loop_var: package

    - name: "Checking whether spacy data is available"
      stat:
         path: "{{ lm_path }}/.spacydata"
      register: spacydata
      changed_when: False

    - when: not spacydata.stat.exists or force is defined
      block:
        - name: "Installing Spacy data locally (Listen carefully, I shall do this only once!)"
          include_role:
              name: lamachine-run
          vars:
              command: "python3 -m spacy download {{ item }}"
          with_items:
              - en
              - de
              - es
              - pt
              - fr
              - it
              - nl
              - xx
          when: locality != "global"

        - name: "Installing Spacy data globally  (Listen carefully, I shall do this only once!)"
          become: "{{lm_become}}"
          become_user: root
          shell:
              command: "python3 -m spacy download {{ item }}"
          with_items:
              - en
              - de
              - es
              - pt
              - fr
              - it
              - nl
              - xx
          when: locality == "global"

        - name: "Marking spacy data as installed"
          copy:
            content: ""
            dest: "{{lm_path}}/.spacydata"


