---

    - name: Output warning
      debug:
        msg: "asr4J requires access to a private gitlab server and will fail if you do not have access (based on ssh keypairs)"

    - name: Installing asr4J python package
      include_role:
        name: lamachine-python-install
      vars:
        package:
          name: "asr4J"
          git_url: "git@gitlab.science.ru.nl:ltenbosch/asr4J.git"

    - name: Register webservice
      include_role:
          name: lamachine-register
      vars:
        update: "asr4J"
        package:
           pip: "asr4J"
        allow_failure: yes #in case the app is not installed
        metadata: #add entrypoint metadata to registry
            identifier: "asr4J"
            entryPoints:
              - { "@type": "EntryPoint",  urlTemplate: "{{lm_base_url}}/asr4J", interfaceType: "WUI" }
              - { "@type": "EntryPoint",  urlTemplate: "{{lm_base_url}}/asr4J", interfaceType: "REST", specification: "{{lm_base_url}}/asr4J/info" }

    - name: Installing web service
      include_role:
        name: lamachine-web-install
      vars:
        service:
          nginx: asr4J
          clam: asr4J
          uwsgi: asr4J

    - name: Link Python package installation in opt/
      include_role:
        name: lamachine-python-link
      with_items:
        - asr4J
