---
    - name: "Outputting temporary metadata"
      copy:
        content: '{% if "metadata" in package %}{{ metadata_defaults|combine(metadata)|combine(package.metadata)|to_json }}{% else %}{{ metadata_defaults|combine(metadata)|to_json }}{% endif %}'
        dest: "{{lm_prefix}}/var/tmpmetadata.json"
        force: yes

    - name: "Registering metadata"
      shell: |
        #!/bin/bash
        {% if 'pip' in package and package.pip %}
        pip3 show -v {{package.pip}} | {{lm_prefix}}/bin/codemetapy --with-entrypoints -r {{lm_prefix}}/var/lamachine-registry.json -i {% if codemeta %}json,{% endif %}json,pip {% if codemeta %}{{codemeta}}{% endif %} {{lm_prefix}}/var/tmpmetadata.json -
        {% else %}
        {{lm_prefix}}/bin/codemetapy --with-entrypoints -r {{lm_prefix}}/var/lamachine-registry.json -i {% if codemeta %}json,{% endif %}json {% if codemeta %}{{codemeta}}{% endif %} {{lm_prefix}}/var/tmpmetadata.json
        {% endif %}
        exit $?
      args:
        executable: /bin/bash
      environment: "{{lm_env}}"
