---

    - name: Installing FLAT settings
      template:
          src: "flat_settings.py"
          dest: "{{lm_prefix}}/etc/flat_settings.py"
          force: yes
          backup: yes
          owner: "{{unix_user}}"
          mode: u+rw,a+r

    - name: Applying migrations
      become: "{{lm_become}}"
      become_user: "{{web_user}}"
      shell: "DJANGO_SETTINGS_MODULE=flat_settings django-admin migrate --run-syncdb"
      args:
          executable: /bin/bash
          chdir: "{{lm_prefix}}/etc"}
      environment: "{{lm_env}}"

    - name: Create FLAT superuser
      become: "{{lm_become}}"
      become_user: "{{web_user}}"
      shell: |
        echo -n "
        from django.contrib.auth.models import User

        username = 'flat'
        password = 'flat'
        email = 'flat@localhost'

        if User.objects.filter(username=username).count() == 0:
            User.objects.create_superuser(username, email, password)
            print('Superuser created.')
        else:
            print('Superuser creation skipped.')
        " | django-admin shell -i python
      args:
          executable: /bin/bash
          chdir: "{{lm_prefix}}/etc"
      environment: "{{lm_env}}"
