---

    - name: Installing Python packages
      include_role:
        name: python-install
      vars:
        github_user: "{{item.github_user}}"
        github_repo: "{{item.github_repo}}"
        pip_package: "{{item.pip_package}}"
        conda_package: "{{item.conda_package}}"
      with_items:
          - { github_user: "proycon", github_repo: "pynlpl", pip_package: "pynlpl", conda_package: "" }
          - { github_user: "proycon", github_repo: "clam", pip_package: "clam", conda_package: "" }
          - { github_user: "proycon", github_repo: "folia", pip_package: "folia-tools", conda_package: "" }
          - { github_user: "proycon", github_repo: "babelpy", pip_package: "babelpy", conda_package: "" }
          - { github_user: "proycon", github_repo: "babelente", pip_package: "babelente", conda_package: "" }

    - name: Testing Python packages
      shell: |
          if [ {{prefer_global|int}} -ne 1 ]; then
              source {{homedir}}/bin/lamachine-{{ conf_name }}.activate
          fi
          hash -r  #clear cache
          echo "PATH=$PATH">&2
          echo "LD_LIBRARY_PATH=$LD_LIBRARY_PATH">&2
          echo "VIRTUAL_ENV=$VIRTUAL_ENV">&2
          echo "PYTHONPATH=$PYTHONPATH">&2
          python -c "import {{ item }}"
      args:
          executable: /bin/bash
      with_items:
          - pynlpl.formats.folia
          - pynlpl

    - name: Testing whether python-based tools start
      shell: |
          if [ {{prefer_global|int}} -ne 1 ]; then
              source {{homedir}}/bin/lamachine-{{ conf_name }}.activate
          fi
          hash -r  #clear cache
          echo "PATH=$PATH">&2
          echo "LD_LIBRARY_PATH=$LD_LIBRARY_PATH">&2
          echo "VIRTUAL_ENV=$VIRTUAL_ENV">&2
          echo "PYTHONPATH=$PYTHONPATH">&2
          which {{item}}>&2 || true
          {{ item }} -h
      args:
          executable: /bin/bash
      with_items:
          - foliavalidator
          - clamservice
          - folia2html
          - folia2txt
          - foliaquery
          - babelente

