---

    - name: Installing Python packages
      include_role:
        name: python-install
      with_items:
          - { github_user: "proycon", github_repo: "pynlpl", pip: "pynlpl", conda: "" }
          - { github_user: "proycon", github_repo: "clam", pip: "clam", conda: "" }
          - { github_user: "proycon", github_repo: "folia", pip: "folia-tools", conda: "" }
          - { github_user: "proycon", github_repo: "babelpy", pip: "babelpy", conda: "" }
          - { github_user: "proycon", github_repo: "babelente", pip: "babelente", conda: "" }
      loop_control:
           loop_var: package

    - name: Testing Python packages
      include_role:
          name: lamachine_run
      vars:
          command: "python -c 'import {{ item }}'"
      with_items:
          - pynlpl
          - pynlpl.formats.folia
      register: test
      changed_when: test.rc != 0

    - name: Testing whether python-based tools start
      include_role:
          name: lamachine_run
      vars:
          command: "{{ item }} -h"
      with_items:
          - foliavalidator
          - clamservice
          - folia2html
          - folia2txt
          - foliaquery
          - babelente
      register: test
      changed_when: test.rc != 0

