---

    - name: Installing Python packages
      include_role:
        name: lamachine-python-install
      with_items:
          - { github_user: "proycon", github_repo: "pynlpl", pip: "pynlpl" }
          - { github_user: "proycon", github_repo: "clam", pip: "clam" }
          - { github_user: "proycon", github_repo: "folia", pip: "folia-tools" }
          - { github_user: "proycon", github_repo: "foliadocserve", pip: "foliadocserve" }
          - { github_user: "proycon", github_repo: "babelpy", pip: "babelpy" }
          - { github_user: "proycon", github_repo: "babelente", pip: "babelente" }
      loop_control:
           loop_var: package

    - name: Testing Python packages
      include_role:
          name: lamachine-run
      vars:
          command: "python3 -c 'import {{ item }}'"
      with_items:
          - pynlpl
          - pynlpl.formats.folia
      register: test
      changed_when: test.rc != 0

    - name: Testing whether python-based tools start
      include_role:
          name: lamachine-run
      vars:
          command: "{{ item }} -h"
      with_items:
          - foliavalidator
          - clamservice
          - folia2html
          - folia2txt
          - foliaquery
          - babelente
      register: test
      changed_when: test.rc != 0

    - when: webserver
      block:
        - name: Installing FLAT
          include_role:
            name: lamachine-python-install
          vars:
            package:
               github_user: "proycon"
               github_repo: "flat"
               pip: "FoLiA-Linguistic-Annotation-Tool"
            metadata:
               entryPoints: { "@type": "EntryPoint",  url: "{{lm_base_url}}/flat" }


        - name: Installing webservices
          include_role:
            name: lamachine-python-install
          vars:
            package:
               github_user: "proycon"
               github_repo: "clamservices"
               pip: "clamservices"

        - name: Reading Software Metadata Registry
          vars:
            file: "{{lm_prefix}}/var/lamachine-registry.json"
            name: codemeta_registry

        - name: Register webservices
          include_role:
              name: lamachine-register
          vars:
              metadata: #add entrypoint metadata to registry
                  identifier: "{{item}}"
                  entryPoints: { "@type": "EntryPoint",  urlTemplate: "{{lm_base_url}}/{{item}}", mediatorApplication: "#clamservices" }
          when: '"all" in services or item in services'
          with_items:
            - frog
            - ucto
            - timbl
            - colibricore

        - name: Link Python package installation in opt/
          become: "{{lm_become}}"
          become_user: root
          shell: |
            export DIR=$(python3 -c "import {{item}}; print({{item}}.__path__[0])")
            if [ ! -e "$DIR" ]; then
                echo "Unable to find dir"
                exit 2
            fi
            ln -sf $DIR {{lm_prefix}}/opt/{{item}}
          with_items:
            - clam
            - clamservices
            - django
            - flat
          environment: "{{lm_env}}"

        - name: "Install webserver configuration"
          become: "{{lm_become}}"
          become_user: root
          template:
            src: "nginx/clamservices.conf"
            dest: "{{lm_prefix}}/etc/nginx/conf.d/clamservices.conf"
            force: yes
            backup: yes
            owner: "{{unix_user}}"
            group: "{{unix_group}}"
          when: webservertype == "nginx" and ("all" in services or "ucto"  in services or "frog" in services or "timbl" in services or "colibricore" in services)

        - name: "Install uwsgi configurations,"
          become: "{{lm_become}}"
          become_user: root
          template:
            src: "uwsgi/{{item}}.ini"
            dest: "{{lm_prefix}}/etc/uwsgi-emperor/vassals/{{item}}.ini"
            force: yes
            backup: yes
            owner: "{{web_user}}" #permissions need to match the runner
            group: "{{web_group}}"
            mode: u+rw,a+r
          when: '"all" in services or item in services'
          with_items:
            - frog
            - ucto
            - timbl
            - colibricore

        - name: "Install clam configuration"
          become: "{{lm_become}}"
          become_user: root
          template:
            src: "clam/{{item}}.config.yml"
            dest: "{{lm_prefix}}/etc/{{item}}.config.yml"
            force: yes
            backup: yes
            owner: "{{unix_user}}"
            group: "{{unix_group}}"
            mode: u+rw,a+r
          when: '"all" in services or item in services'
          with_items:
            - frog
            - ucto
            - timbl
            - colibricore

        - name: "Setting up FLAT"
          import_tasks: flat.yml
          when: '"all" in services or "flat" in services'
