- name: Get latest release of "{{ user }}/{{ repo }}"
  github_release:
    user: "{{ user }}"
    repo: "{{ repo }}"
    action: latest_release
  register: requested_version
  when: version == "stable"

- name: Get latest development version of "{{ user }}/{{ repo }}"
  vars:
    requested_version: "HEAD" #the very latest HEAD of the master branch
  when: version == "development"

- name: Get custom version of "{{ user }}/{{ repo }}"
  vars:
    requested_version: "{{ customversion[repo] }}" #the very latest HEAD of the master branch
  when: version == "custom"

- git:
    repo: "https://github.com/{{ user }}/{{ repo }}"
    dest: "{{ source_path }}/ticcutils"
    version: "{{ requested_version }}"
    update: yes #retrieve new versions
  when: requested_version exists

- ac_compile:
    pkg_source_dir: "{{ source_path }}/{{ repo }}"

