{% if clam_include %}
include: "{{clam_include}}"
{% endif %}
port: 8802
urlprefix: "ucto"
root: "{{www_data_path}}/ucto.clam/"
bindir: "{{lm_prefix}}/bin/"
{% if "switchboard" in remote_services and remote_services.switchboard %}
switchboard_forward_url: "{{remote_services.switchboard}}/#/ucto/$BACKLINK/$MIMETYPE/$LANGUAGE"
{% endif %}
