{% if clam_include %}
include: "{{clam_include}}"
{% endif %}
port: 8802
urlprefix: "ucto"
root: "{{www_data_path}}/ucto.clam/"
bindir: "{{lm_prefix}}/bin/"
switchboard_forward_url: "https://switchboard.clarin.eu/#/ucto/$BACKLINK/$MIMETYPE/$LANGUAGE"
