---
    - name: Installing T-scan
      include_role:
        name: lamachine-git-autoconf
      vars:
          package:
            repo: tscan
            user: proycon

    #download data is done in tscan bootstrap.sh already
    #
    #TODO: set up webservice?
