---
    - name: Installing T-scan
      include_role:
        name: lamachine-git-autoconf
      vars:
          package:
            repo: tscan
            user: proycon
          metadata:
            developers: [ Ko van der Sloot, Martijn van der Klis, Maarten van Gompel ]
            summary: "T-scan: an analysis tool for dutch texts to assess the complexity of the text, based on original work by Rogier Kraf"
            license: AGPL

    #download data is done in tscan bootstrap.sh already
    #
    #TODO: set up webservice?
