---


    - name: Check for unsupported OS for PICCL
      debug:
        msg: "PICCL is not supported on Mac OS X"
      when: ansible_distribution|lower == "macosx"

    - name: Installing global dependencies for PICCL
      include_role:
        name: lamachine-package-install
      with_items:
        - { debian: tesseract-ocr, redhat: tesseract, arch: tesseract }
        - { debian: tesseract-ocr-eng, arch: tesseract-data-eng } #English is already included on redhat? no package tesseract-data-eng
        - { debian: tesseract-ocr-nld, redhat: tesseract-langpack-nld, arch: tesseract-data-nld }
        - { debian: tesseract-ocr-deu, redhat: tesseract-langpack-deu, arch: tesseract-data-deu }
        - { debian: tesseract-ocr-deu-frak, redhat: tesseract-langpack-deu_frak, arch: tesseract-data-deu_frak }
        - { debian: tesseract-ocr-fra, redhat: tesseract-langpack-fra, arch: tesseract-data-fra }
        - { debian: poppler-utils, redhat: poppler-utils, arch: poppler }
        - { debian: djvulibre-bin, redhat: djvulibre, arch: djvulibre }
        - { debian: libdjvulibre-text }
        - { debian: imagemagick, redhat: ImageMagick, arch: imagemagick }
        - { debian: perl, redhat: perl, arch: perl }
      loop_control:
          loop_var: package

    - name: Installing TICCLtools
      include_role:
        name: lamachine-git-autoconf
      vars:
        package:
          repo: ticcltools
          user: LanguageMachines

    - name: Create nextflow home
      file:
        path: "{{lm_prefix}}/opt/nextflow"
        state: directory

    - name: Install Nextflow
      shell: curl -fsSL https://get.nextflow.io | bash
      args:
        chdir: "{{lm_prefix}}/bin" #this is where the nextflow binary will be written
      environment:
        NXF_HOME: "{{lm_prefix}}/opt/nextflow"

    - name: Register Nextflow
      include_role:
         name: lamachine-register
      vars:
         metadata:
           identifier: nextflow
           name: Nextflow
           author: [ "Paolo Di Tommaso", "Maria Chatzou", "Evan W Floden", "Pablo Prieto Barja", "Emilio Palumbo", "Cedric Notredame" ]
           url: "https://www.nextflow.io"
           license: GPL

    - name: Nextflow test
      include_role:
          name: lamachine-run
      vars:
          command: "nextflow -version"

    - name: Ensure nextflow script permissions are sane
      shell: |
        chmod a+rx {{lm_prefix}}/bin/nextflow
        find {{ lm_prefix }}/opt/nextflow -type f | xargs chmod 0644
        find {{ lm_prefix }}/opt/nextflow -type d | xargs chmod 0755

    - name: "Adding activation script for Nextflow"
      become: "{{lm_become}}"
      become_user: root
      copy:
        dest: "{{lm_prefix}}/bin/activate.d/nextflow.sh"
        content: |
          export NXF_HOME={{lm_prefix}}/opt/nextflow
        mode: u+rwx,a+rx

    - name: Install PICCL
      include_role:
        name: lamachine-git
      vars:
        package:
          user: LanguageMachines
          repo: PICCL

    - name: "Symlink PICCL in {{lm_prefix}}/opt"
      file:
        src: "{{source_path}}/PICCL"
        dest: "{{lm_prefix}}/opt/PICCL"
        state: link

    - name: Make PICCL nextflow scripts available in environment
      shell: |
        cp -sf {{lm_prefix}}/opt/PICCL/*.nf .
      args:
        chdir: "{{lm_prefix}}/bin"


    - name: "Download data and example corpora for PICCL"
      shell: |
        if [ ! -d data ]; then
          ./download-data.nf
        fi
        if [ ! -d corpora ]; then
          ./download-examples.nf
        fi
      args:
        chdir: "{{lm_prefix}}/opt/PICCL"
      environment: "{{lm_env}}"

    - when: webserver and ("piccl" in services or "all" in services)
      block:
        - name: Detect current PICCL branch or tag
          shell: "git branch | grep '^\\*' | sed -e 's/(detached from \\(.*\\))/\\1/' -e 's/\\* //'"
          register: current_piccl_branch_or_tag
          args:
            chdir: "{{source_path}}/PICCL"
        - name: Installing PICCL webservice
          include_role:
            name: lamachine-python-install
          vars:
            package:
              github_user: "LanguageMachines"
              github_repo: "PICCL"
              setupdir: "webservice" #setup.py is in this subdir
              git_branch: "{{ current_piccl_branch_or_tag.stdout }}"
            do_registration: false #we register entrypoints manually:

        - name: Registering PICCL webservice entrypoints
          include_role:
            name: lamachine-register
          vars:
            update: piccl
            metadata:
              identifier: piccl
              entryPoints:
                - { "@type": "EntryPoint", urlTemplate: "{{lm_base_url}}/piccl", interfaceType: "WUI" }
                - { "@type": "EntryPoint", urlTemplate: "{{lm_base_url}}/piccl", specification: "{{lm_base_url}}/piccl/info",  interfaceType: "REST" }

        - name: "Install webserver configuration for PICCL"
          become: "{{lm_become}}"
          become_user: root
          template:
            src: "nginx/piccl.conf"
            dest: "{{lm_prefix}}/etc/nginx/conf.d/piccl.conf"
            force: yes
            backup: yes
            owner: "{{unix_user}}"
          when: webservertype == "nginx"

        - name: "Install uwsgi configuration for PICCL"
          become: "{{lm_become}}"
          become_user: root
          template:
            src: "uwsgi/piccl.ini"
            dest: "{{lm_prefix}}/etc/uwsgi-emperor/vassals/piccl.ini"
            force: yes
            backup: yes
            owner: "{{web_user}}"
            group: "{{web_group}}"

        - name: "Install clam configuration for PICCL"
          become: "{{lm_become}}"
          become_user: root
          template:
            src: "clam/piccl.config.yml"
            dest: "{{lm_prefix}}/etc/piccl.config.yml"
            force: yes
            backup: yes
            owner: "{{unix_user}}"
