---
    #- name: Failing if authorization is not properly configured
    #  fail:
      #    msg: "You did not set fame_user and fame_password in your configuration. This is required for forcedalignment to work! If you do not have the credentials yet, contact h.vandenheuvel@let.ru.nl to request access."
    #  when: fame_user == "undefined" or fame_password == "undefined"

    - name: Installing webservice
      include_role:
        name: lamachine-python-install
      vars:
        package:
           name: "forcedalignment2"
           github_user: "opensource-spraakherkenning-nl"
           github_repo: "forcedalignment2"
           metadata:
              identifier: "forcedalignment2"


    - name: Removing old resources (if present)
      file:
          path: "{{lm_prefix}}/opt/forcedalignment2_resources"
          state: absent
      ignore_errors: yes #in case it isn't there in the first place

    - name: Creating directory for resources
      become: "{{lm_become}}"
      become_user: root
      file:
          path: "{{lm_prefix}}/opt/forcedalignment2_resources"
          state: directory
          owner: "{{unix_user}}"
          group: "{{unix_group}}"
          mode: u+rwx,g+rwsx,a+rx

    - name: Downloading resources
      get_url:
        url: https://applejack.science.ru.nl/downloads/forcedalignment/forcedalignment2_resources.tar.gz
        dest: "{{lm_prefix}}/opt/forcedalignment2_resources/forcedalignment2_resources.tar.gz"
        tmp_dest: "{{lm_prefix}}/opt/forcedalignment2_resources"


    - name: Finalising resource installation
      shell: |
          #!/bin/bash
          tar xzf forcedalignment2_resources.tar.gz
          rm -rf forcedalignment2_resources.tar.gz
          mv resources/* .
          mv resources2/* .
          chown -R {{unix_user}}:{{unix_group}} .
          find . -type d | xargs chmod u+rw,g+rw,a+rx
          find . -type f | xargs chmod u+rw,g+rw,a+r
      args:
          chdir: "{{lm_prefix}}/opt/forcedalignment2_resources"

    - name: Installing web service
      include_role:
        name: lamachine-web-install
      vars:
        service:
          nginx: forcedalignment2
          clam: forcedalignment2
          uwsgi: forcedalignment2

    - name: Link Python package installation in opt/
      include_role:
        name: lamachine-python-link
      with_items:
        - forcedalignment2

    - name: Register webservice metadata
      include_role:
          name: lamachine-register
      vars:
          update: "{{item}}"
          metadata: #add entrypoint metadata to registry
              identifier: "{{item}}"
              entryPoints:
                - { "@type": "EntryPoint",  urlTemplate: "{{lm_base_url}}/{{item}}", interfaceType: "WUI", mediatorApplication: "#forcedalignment2" }
                - { "@type": "EntryPoint",  urlTemplate: "{{lm_base_url}}/{{item}}", interfaceType: "REST", specification: "{{lm_base_url}}/{{item}}/info",  mediatorApplication: "#forcedalignment2" }
      when: '"all" in services or item in services'
      with_items:
        - forcedalignment2


