---
    - name: Installing global dependencies for forcedalignment2
      include_role:
        name: lamachine-package-install
      with_items:
        - { debian: dos2unix, redhat: dos2unix, arch: dos2unix }
        - { debian: perl, redhat: perl, arch: perl }
      loop_control:
          loop_var: package

    - name: "Installing python dependencies for forcedalignment2"
      include_role:
         name: lamachine-python-install
      with_items:
        - { "pip": numpy }
        - { "pip": pandas }
      loop_control:
          loop_var: package
      when: minimal is not defined or not minimal

    - name: Installing webservice
      include_role:
        name: lamachine-python-install
      vars:
        package:
           name: "forcedalignment2"
           github_user: "opensource-spraakherkenning-nl"
           github_repo: "forcedalignment2"
           metadata:
              identifier: "forcedalignment2"

    - name: Removing old resources (if present)
      file:
          path: "{{lm_prefix}}/opt/forcedalignment2_resources"
          state: absent
      ignore_errors: yes #in case it isn't there in the first place

    - name: Creating directory for resources
      become: "{{lm_become}}"
      become_user: root
      file:
          path: "{{lm_prefix}}/opt/forcedalignment2_resources"
          state: directory
          owner: "{{unix_user}}"
          group: "{{unix_group}}"
          mode: u+rwx,g+rwsx,a+rx

    - name: Copying resources from git source
      become: "{{lm_become}}"
      become_user: root
      shell: cp -Rpd {{source_path}}/forcedalignment2/resources/* {{lm_prefix}}/opt/forcedalignment2_resources/

    - name: Downloading and extracting resources
      shell: |
        #!/bin/bash
          ./download_resources.sh --force || exit 1
          chown -R {{unix_user}}:{{unix_group}} .
          find . -type d | xargs chmod u+rw,g+rw,a+rx
          find . -type f | xargs chmod u+rw,g+rw,a+r
      args:
          chdir: "{{lm_prefix}}/opt/forcedalignment2_resources"

    - name: Installing web service
      include_role:
        name: lamachine-web-install
      vars:
        service:
          nginx: forcedalignment2
          clam: forcedalignment2
          uwsgi: forcedalignment2

    - name: Link Python package installation in opt/
      include_role:
        name: lamachine-python-link
      with_items:
        - forcedalignment2

    - name: Register webservice metadata
      include_role:
          name: lamachine-register
      vars:
          update: "{{item}}"
          metadata: #add entrypoint metadata to registry
              identifier: "{{item}}"
              entryPoints:
                - { "@type": "EntryPoint",  urlTemplate: "{{lm_base_url}}/{{item}}", interfaceType: "WUI", mediatorApplication: "#forcedalignment2" }
                - { "@type": "EntryPoint",  urlTemplate: "{{lm_base_url}}/{{item}}", interfaceType: "REST", specification: "{{lm_base_url}}/{{item}}/info",  mediatorApplication: "#forcedalignment2" }
      when: '"all" in services or item in services'
      with_items:
        - forcedalignment2


