---
lamachine_version: "2.4.5" #also change in bootstrap.sh and codemeta.json
conf_name: "default"
version: "stable" #stable, development or custom
controller: internal
lamachine_path: "." #path to cloned LaMachine git repo
homedir: "/home/{{unix_user}}"
local_prefix: "{{homedir}}/lamachine-{{conf_name}}" #where local packages are installed
global_prefix: "/usr/local" #where global packages are installed
data_path: "/data"
locality: "global" #Install everything globally
localenv_type: "virtualenv" #Local environment type, can be conda or virtualenv
webserver: false
webservertype: "nginx"
unix_group: "{{unix_user}}"
web_user: "{{unix_user}}"
web_group: "{{web_user}}"
maintainer_name: "{{unix_user}}" #The name of the person maintaining this LaMachine installation
maintainer_mail: "{{unix_user}}@{{hostname}}" #Maintainer mail
http_port: 80 #webserver port
services:
  - all
lab: true #Enable Jupyter Lab environment, note that this opens the system to arbitrary code execution and file system access! (provided the below password is known)
lab_password_sha1: "sha1:fa40baddab88:c498070b5885ee26ed851104ddef37926459b0c4" #default password: lamachine
lab_allow_origin: "*" #hosts that may access the lab environment
flat_password: "flat" #admin password for flat
# defaults file for miniconda (not used now)
miniconda_mirror : https://repo.continuum.io/miniconda
miniconda_python_ver : 3
miniconda_ver: "latest"
miniconda_platform : '{% if ansible_system == "Darwin" %}MacOSX{% else %}{{ansible_system}}{% endif %}-{{ansible_machine}}'
miniconda_name : 'Miniconda{{miniconda_python_ver}}-{{miniconda_ver}}-{{miniconda_platform}}'
miniconda_installer_sh : '{{miniconda_name}}.sh'
miniconda_installer_url : '{{miniconda_mirror}}/{{miniconda_installer_sh}}'
# defaults for producer metadata:
github_clst_users:
  - LanguageMachines
  - proycon
  - kosloot
  - fkunneman
  - erkanbasar
metadata_extra: [] #Extra metadata to register, consist of list of dictionaries, may have a url field, codemeta field, or metadata block that will be passed to the registry
metadata_producer_unknown: {}
metadata_producer_clst:
    "@id": "https://www.ru.nl/clst"
    "@type": "Organization"
    name: "Centre for Language and Speech Technology"
    url: "https://www.ru.nl/clst"
    parentOrganization:
        "@id": "https://www.ru.nl/cls"
        "@type": "Organization"
        name: "Centre for Language Studies"
        url: "https://www.ru.nl/cls"
        parentOrganization:
            "@id": "https://www.ru.nl"
            name: "Radboud University"
            "@type": "Organization"
            url: "https://www.ru.nl"
            location:
                "@type": "Place"
                name: "Nijmegen"
metadata_producer_cls:
    "@id": "https://www.ru.nl/cls"
    "@type": "Organization"
    name: "Centre for Language Studies"
    url: "https://www.ru.nl/cls"
    parentOrganization:
        "@id": "https://www.ru.nl"
        name: "Radboud University"
        "@type": "Organization"
        url: "https://www.ru.nl"
        location:
            "@type": "Place"
            name: "Nijmegen"
