---

- name: "{{pkg_name}} - Invoke bootstrap if it exists"
  shell: |
    if [ -f ./bootstrap.sh ]; then
      bash ./bootstrap.sh
      exit $?
    elif [ -f ./bootstrap ]; then
      bash bootstrap
      exit $?
    else
      exit 0 #no bootstrap, should be fine?
    fi
  args:
      chdir: "{{ pkg_source_dir }}"
  register: bootstrap_result

- name: "{{pkg_name}} - Invoke configure"
  command: "./configure --prefix={% if not root or prefer_local %}{{ local_prefix }}{% else %}{{ global_prefix }}{% endif %} {% if configure_opts is defined %}{{configure_opts}}{% endif %}"
  args:
      chdir: "{{ pkg_source_dir }}"
  environment: "{{ build_environment }}"
  register: configure_result

- name: "{{pkg_name}} - Invoke make"
  command: "make {% if make_opts is defined %}{{make_opts}}{% endif %}"
  args:
       chdir: "{{ pkg_source_dir }}"
  environment: "{{ build_environment }}"
  when: configure_result.rc == 0
  register: make_result

- name: "{{pkg_name}} - Invoke make install"
  become: "{% if root and not prefer_local %}true{% else %}false{% endif %}"
  become_user: root
  become_method: sudo
  command: "make install {% if make_install_opts is defined %}{{make_install_opts}}{% endif %}"
  args:
       chdir: "{{ pkg_source_dir }}"
  environment: "{{ build_environment }}"
  register: make_install_result
  when: configure_result.rc == 0 and make_result.rc == 0
