---

- name: "{{pkg_name}} - Invoke bootstrap if it exists"
  shell: |
    if [ -f ./bootstrap.sh ]; then
      bash ./bootstrap.sh
      exit $?
    elif [ -f ./bootstrap ]; then
      bash bootstrap
      exit $?
    else
      exit 0 #no bootstrap, should be fine?
    fi
  args:
      chdir: "{{ pkg_source_dir }}"
  register: bootstrap_result


- name: "{{pkg_name}} - Invoke configure (local)"
  command: "./configure --prefix={{ local_prefix }}"
  args:
      chdir: "{{ pkg_source_dir }}"
  register: configure_result
  when: not root or prefer_local

- name: "{{pkg_name}} - Invoke configure (global)"
  command: "./configure --prefix={{ global_prefix }}"
  args:
      chdir: "{{ pkg_source_dir }}"
  register: configure_result
  when: root and not prefer_local

- name: "{{pkg_name}} - Invoke make"
  command: "make"
  args:
       chdir: "{{ pkg_source_dir }}"
  when: configure_result.rc == 0
  register: make_result

- name: "{{pkg_name}} - Invoke make install (local)"
  command: "make install"
  args:
       chdir: "{{ pkg_source_dir }}"
  register: make_install_result
  when: (not root and prefer_local) and configure_result.rc == 0 and configure_result.rc == 0

- name: "{{pkg_name}} - Invoke make install (global)"
  become: "{{ root and not prefer_local }}"
  become_user: root
  become_method: sudo
  command: "make install"
  args:
       chdir: "{{ pkg_source_dir }}"
  register: make_install_result
  when: configure_result.rc == 0 and configure_result.rc == 0 and make_result.rc == 0
