---

    - name: "{% if 'debian' in package %}{{package.debian}}{% else %}(NOT APPLICABLE){% endif %} - Installing global dependency (Debian/Ubuntu)"
      become: true
      become_user: root
      apt:
        name: "{{package.debian}}"
        state: installed
      when: root and "debian" in package and (ansible_distribution|lower == "debian" or ansible_distribution|lower == "ubuntu" or  ansible_distribution|lower == "linuxmint")

    - name: "{% if 'redhat' in package %}{{package.redhat}}{% else %}(NOT APPLICABLE){% endif %} - Installing global dependency (RedHat)"
      become: true
      become_user: root
      yum:
        name: "{{package.redhat}}"
        state: installed
      when: root and "redhat" in package and (ansible_distribution|lower == "redhat" or ansible_distribution|lower == "centos" or  ansible_distribution|lower == "fedora" or ansible_distribution|lower == "rhel")

    - name: "{% if 'arch' in package %}{{package.arch}}{% else %}(NOT APPLICABLE){% endif %} - Installing global dependency (Arch)"
      become: true
      become_user: root
      pacman:
        name: "{{package.arch}}"
        state: installed
      when: root and "arch" in package and (ansible_distribution|lower == "arch")

    - name: "{% if 'homebrew' in package %}{{package.homebrew}}{% else %}(NOT APPLICABLE){% endif %} - Installing global dependency (Mac OS X/Homebrew)"
      homebrew:
        name: "{{package.homebrew}}"
        state: installed
      when: '"homebrew" in package and (ansible_distribution|lower == "macosx")'
