---
    - name: Installing Valkuil
      include_role:
        name: lamachine-git
      vars:
        package:
            user: proycon
            repo: valkuil-gecco

    - name: Check if models already downloaded
      stat:
        path: "{{ source_path }}/valkuil-gecco/models/ValkuilCorpus.spacing.colibri.patternmodel"
      register: valkuil_model

    - name: Downloading Valkuil models
      include_role:
          name: lamachine-run
      vars:
          command: ./download-models.sh
          chdir: "{{source_path}}/valkuil-gecco"
      when: not valkuil_model.stat.exists

    - name: Installing valkuil webservice
      include_role:
        name: lamachine-python-install
      vars:
        package:
           github_user: "proycon"
           github_repo: "valkuil-gecco"

    - name: Installing web service
      include_role:
        name: lamachine-web-install
      vars:
        service:
          nginx: valkuil
          clam: valkuil
          uwsgi: valkuil

    - name: Link Python package installation in opt/
      include_role:
        name: lamachine-python-link
      with_items:
        - valkuilwebservice

    - name: Creating run directory
      become: "{{lm_become}}"
      become_user: root
      file:
        path: "{{ lm_prefix }}/src/valkuil-gecco/run"
        state: directory
        owner: "{{web_user}}"
        group: "{{web_group}}"
        mode: u+rwX,g+rwsX,a+rX
      ignore_errors: yes

    - name: Recursively setting run permissions
      become: "{{lm_become}}"
      become_user: root
      file:
        path: "{{ lm_prefix }}/src/valkuil-gecco/run"
        state: directory
        owner: "{{web_user}}"
        group: "{{web_group}}"
        mode: u+rwX,g+rwX,a+rX
        recurse: yes
      ignore_errors: yes

    - name: Registering Valkuil webservice entrypoints
      include_role:
        name: lamachine-register
      vars:
        update: valkuil-gecco
        metadata:
          identifier: valkuil-gecco
          entryPoints:
              - { "@type": "EntryPoint", name: "Valkuil interface", urlTemplate: "{{lm_base_url}}/valkuil", interfaceType: "WUI" }
              - { "@type": "EntryPoint", urlTemplate: "{{lm_base_url}}/valkuil", specification: "{{lm_base_url}}/valkuil/info",  interfaceType: "REST" }


