---
    - name: Installing Valkuil
      include_role:
        name: lamachine-git
      vars:
        package:
            user: proycon
            repo: valkuil-gecco
            metadata:
                name: Valkuil.net
                entryPoints:
                    - { "@type": "EntryPoint", name: "Generic Valkuil interface", urlTemplate: "{{lm_base_url}}/valkuil", interfaceType: "WUI" }
                    - { "@type": "EntryPoint", urlTemplate: "{{lm_base_url}}/valkuil", specification: "{{lm_base_url}}/valkuil/info",  interfaceType: "REST" }

    - name: Check if models already downloaded
      stat:
        path: "{{ source_path }}/valkuil-gecco/models/ValkuilCorpus.spacing.colibri.patternmodel"
      register: valkuil_model

    - name: Downloading Valkuil models
      include_role:
          name: lamachine-run
      vars:
          command: ./download-models.sh
          chdir: "{{source_path}}/valkuil-gecco"
      when: not valkuil_model.stat.exists

    - name: Installing valkuil webservice
      include_role:
        name: lamachine-python-install
      vars:
        package:
           github_user: "proycon"
           github_repo: "valkuil-gecco"





