{% if clam_include %}
include: "{{clam_include}}"
{% endif %}
port: 8818
urlprefix: "spacy"
root: "{{www_data_path}}/spacy.clam/"
bindir: "{{lm_prefix}}/bin/"
{% if "switchboard" in remote_services and remote_services.switchboard %}
switchboard_forward_url: "{{remote_services.switchboard}}/#/spacy/$BACKLINK/$MIMETYPE"
{% endif %}
