---
    - name: Installing FreeLing for macOS
      homebrew:
        name: "freeling"
        state: present
      when: (ansible_distribution|lower == 'macosx')

    - when: (ansible_distribution|lower != 'macosx')
      block:
      - name: Installing global dependencies for FreeLing
        include_role:
          name: lamachine-package-install
        with_items:
          - { debian: cmake, redhat: cmake, arch: cmake }
          - { debian: swig, redhat: swig, arch: swig } #need for python library
        loop_control:
            loop_var: package

      - when: (ansible_distribution|lower == "ubuntu" and ansible_distribution_version|string < "18.04") or ansible_distribution|lower == "centos" or ansible_distribution|lower == "rhel"
        block:
          - name: Compiling and installing newer cmake (distribution version is too old) (this take a long time)
            include_role:
              name: lamachine-git-autoconf
            vars:
              package:
                repo: CMake
                user: Kitware

      - name: Obtain FreeLing
        include_role:
          name: lamachine-git
        vars:
          package:
            user: TALP-UPC
            repo: FreeLing

      - name: Compile and install Freeling
        shell: |
          #!/bin/bash
          if [[ "{{force|default(0)}}" == "1" ]]; then
            #remove old build dir
            rm -rf build 2> dev/null
          fi
          mkdir build
          cd build
          cmake -DCMAKE_INSTALL_PREFIX="{{lm_prefix}}" -DPYTHON3_API=ON ..
          make install
        args:
          chdir: "{{source_path}}/FreeLing"
          executable: /bin/bash
