---

    - name: Checking if a C++ compiler is available
      import_role:
        name: check_cc

    - name: Installation on Mac OS X using homebrew
      block:
          - name: Ensuring legacy homebrew/science tap is removed
            shell: brew untap homebrew/science || /usr/bin/true
          - name: Adding homebrew tap
            command: brew tap fbkarsdorp/homebrew-lamachine
          - name: Installing from homebrew
            command: brew install ticcutils libfolia uctodata ucto timbl timblserver mbt frogdata frog  #TODO: add foliautils once merged, and toad
      when: ansible_distribution == 'MacOSX' and root == True and not prefer_local and version == "stable"

    - name: Installation on Arch Linux
      block:
        - name: Installing packages from Arch User Repository
          include_role:
              name: aur
          vars:
              package: "{{ item }}"
          with_items:
            - ticcutils
            - libfolia
            - uctodata
            - ucto
            - timbl
            - timblserver
            - mbt
            - mbtserver
            - frogdata
            - frog
            - foliautils
            - toad
      when: ansible_distribution == 'Arch' and root == True and not prefer_local and version == "stable"

    - name: Generic Installation
      block:
        - name: Installing from LanguageMachines github
          include_role:
            name: ac_github
          with_items:
            - repo: ticcutils
              user: LanguageMachines
            - repo: libfolia
              user: LanguageMachines
            - repo: uctodata
              user: LanguageMachines
            - repo: ucto
              user: LanguageMachines
              build_environment:
                 TEXTCAT_CFLAGS: "{% if ansible_distribution|lower == 'macosx' %}-I/usr/local/opt/libtextcat/include/libtextcat/{% endif %}"
                 TEXTCAT_LIBS: "{% if ansible_distribution|lower == 'macosx' %}-L/usr/local/opt/libtextcat/lib/{% endif %}"
            - repo: timbl
              user: LanguageMachines
            - repo: timblserver
              user: LanguageMachines
            - repo: mbt
              user: LanguageMachines
            - repo: mbtserver
              user: LanguageMachines
            - repo: frogdata
              user: LanguageMachines
            - repo: frog
              user: LanguageMachines
            - repo: foliautils
              user: LanguageMachines
            - repo: toad
              user: LanguageMachines
          loop_control:
              loop_var: package
      when: not ((ansible_distributioni|lower == 'macosx' or ansible_distribution|lower == 'arch') and root == True and not prefer_local and version == "stable")

    - name: Installing Colibri Core from github
      include_role:
        name: ac_github
      vars:
        user: proycon
        repo: colibri-core

    - name: Running ldconfig
      become: yes
      command: ldconfig
      when: root and not prefer_local and ansible_distribution|lower != 'macosx'

    - name: Testing whether tools start
      include_role:
          name: lamachine_run
      vars:
          command: "{{item}} -h"
      with_items:
          - ucto
          - timbl
          - timblserver
          - frog
          - mbt
          - folialint
          - colibri-classencode
          - colibri-patternmodeller
      register: test
      changed_when: test.rc != 0
