---
    - name: Checking if a C++ compiler is available
      import_role:
        name: check_cc

    - name: Installing from LanguageMachines github
      include_role:
        name: ac_github
      vars:
        user: LanguageMachines
        repo: "{{ item }}"
      with_items:
        - ticcutils
        - libfolia
        - uctodata
        - ucto
        - timbl
        - timblserver
        - mbt
        - mbtserver
        - frogdata
        - frog
        - foliautils

    - name: Installing from proycon's github
      include_role:
        name: ac_github
      vars:
        user: proycon
        repo: "{{ item }}"
      with_items:
        - colibri-core
