---

    - name: Installing from LanguageMachines github
      include_role:
        name: ac_github
      vars:
        user: LanguageMachines
        repo: "{{ item }}"
      with_items:
        - ticcutils
        - libfolia
        - uctodata
        - ucto
        - timbl
        - timblserver
        - mbt
        - mbtserver
        - frog
        - foliautils
