---

    - name: Checking if a C++ compiler is available
      import_role:
        name: check_cc

    - name: Installation on Mac OS X using homebrew
      block:
          - name: Ensuring legacy homebrew/science tap is removed
            shell: brew untap homebrew/science || /usr/bin/true
          - name: Adding homebrew tap
            command: brew tap fbkarsdorp/homebrew-lamachine
          - name: Installing from homebrew
            command: brew install ticcutils libfolia uctodata ucto timbl timblserver mbt frogdata frog  #TODO: add foliautils once merged, and toad
      when: ansible_distribution == 'MacOSX' and root == True and not prefer_local and version == "stable"

    - name: Installation on Arch Linux
      block:
        - name: Installing packages from Arch User Repository
          include_role:
              name: aur
          vars:
              package: "{{ item }}"
          with_items:
            - ticcutils
            - libfolia
            - uctodata
            - ucto
            - timbl
            - timblserver
            - mbt
            - mbtserver
            - frogdata
            - frog
            - foliautils
            - toad
      when: ansible_distribution == 'Arch' and root == True and not prefer_local and version == "stable"

    - name: Generic Installation
      block:
        - name: Installing from LanguageMachines github
          include_role:
            name: ac_github
          vars:
            user: LanguageMachines
            repo: "{{ item }}"
          with_items:
            - ticcutils
            - libfolia
            - uctodata
            - ucto
            - timbl
            - timblserver
            - mbt
            - mbtserver
            - frogdata
            - frog
            - foliautils
            - toad
      when: not ((ansible_distribution == 'MacOSX' or ansible_distribution == 'Arch') and root == True and not prefer_local and version == "stable")

    - name: Installing from proycon's github
      include_role:
        name: ac_github
      vars:
        user: proycon
        repo: "{{ item }}"
      with_items:
        - colibri-core

    - name: Running ldconfig
      become: yes
      command: ldconfig
      when: root and not prefer_local and ansible_distribution != 'MacOSX'

    - name: Testing whether tools start
      shell: |
          if [ {{prefer_global|int}} -ne 1 ]; then
              source {{homedir}}/bin/lamachine-{{ conf_name }}.activate
          fi
          hash -r  #clear cache
          echo "PATH=$PATH">&2
          echo "LD_LIBRARY_PATH=$LD_LIBRARY_PATH">&2
          echo "VIRTUAL_ENV=$VIRTUAL_ENV">&2
          {{ item }} -h
      args:
          executable: /bin/bash
      with_items:
          - ucto
          - timbl
          - timblserver
          - frog
          - mbt
          - folialint
          - colibri-classencode
          - colibri-patternmodeller
      register: test
      changed_when: test.rc != 0
