---
    - name: Installing spreek2schrijf python package
      include_role:
        name: lamachine-python-install
      vars:
        package:
          github_user: proycon
          github_repo: spreek2schrijf

    - name: Register webservice
      include_role:
          name: lamachine-register
      vars:
        update: "spreek2schrijf"
        package:
           pip: "spreek2schrijf"
        allow_failure: yes #in case the app is not installed
        metadata: #add entrypoint metadata to registry
            identifier: "spreek2schrijf"
            entryPoints:
              - { "@type": "EntryPoint",  urlTemplate: "{{lm_base_url}}/spreek2schrijf", interfaceType: "WUI" }
              - { "@type": "EntryPoint",  urlTemplate: "{{lm_base_url}}/spreek2schrijf", interfaceType: "REST", specification: "{{lm_base_url}}/spreek2schrijf/info" }

    - name: "Install uwsgi configurations"
      become: "{{lm_become}}"
      become_user: root
      template:
        src: "uwsgi/{{item}}.ini"
        dest: "{{lm_prefix}}/etc/uwsgi-emperor/vassals/{{item}}.ini"
        force: yes
        backup: yes
        owner: "{{web_user}}" #permissions need to match the runner
        group: "{{web_group}}"
        mode: u+rw,a+r
      when: '"all" in services or item in services'
      with_items:
        - spreek2schrijf

    - name: "Install clam configuration"
      become: "{{lm_become}}"
      become_user: root
      template:
        src: "clam/{{item}}.config.yml"
        dest: "{{lm_prefix}}/etc/{{item}}.config.yml"
        force: yes
        backup: yes
        owner: "{{unix_user}}"
        group: "{{unix_group}}"
        mode: u+rw,a+r
      when: '"all" in services or item in services'
      with_items:
        - spreek2schrijf

    - name: "Install webserver configuration for spreek2schrijf"
      become: "{{lm_become}}"
      become_user: root
      template:
        src: "nginx/spreek2schrijf.conf"
        dest: "{{lm_prefix}}/etc/nginx/conf.d/spreek2schrijf.conf"
        force: yes
        backup: yes
        owner: "{{unix_user}}"
      when: webservertype == "nginx"

    - name: Link Python package installation in opt/
      become: "{{lm_become}}"
      become_user: root
      shell: |
        export DIR=$(python3 -c "import {{item}}; print({{item}}.__path__[0])")
        if [ ! -e "$DIR" ]; then
            echo "Unable to find dir"
            exit 2
        fi
        if [ -e "{{lm_prefix}}/opt/{{item}}" ]; then
          rm "{{lm_prefix}}/opt/{{item}}"
        fi
        ln -sf $DIR {{lm_prefix}}/opt/{{item}}
      with_items:
        - spreek2schrijf
      environment: "{{lm_env}}"
