---
    - name: Installing spreek2schrijf python package
      include_role:
        name: lamachine-python-install
      vars:
        package:
          github_user: proycon
          github_repo: spreek2schrijf

    - name: Register webservice
      include_role:
          name: lamachine-register
      vars:
        update: "spreek2schrijf"
        package:
           pip: "spreek2schrijf"
        allow_failure: yes #in case the app is not installed
        metadata: #add entrypoint metadata to registry
            identifier: "spreek2schrijf"
            entryPoints:
              - { "@type": "EntryPoint",  urlTemplate: "{{lm_base_url}}/spreek2schrijf", interfaceType: "WUI" }
              - { "@type": "EntryPoint",  urlTemplate: "{{lm_base_url}}/spreek2schrijf", interfaceType: "REST", specification: "{{lm_base_url}}/spreek2schrijf/info" }

    - name: Installing web service
      include_role:
        name: lamachine-web-install
      vars:
        service:
          nginx: spreek2schrijf
          clam: spreek2schrijf
          uwsgi: spreek2schrijf


    - name: Link Python package installation in opt/
      include_role:
        name: lamachine-python-link
      with_items:
        - spreek2schrijf

    - name: "Download and set up data for spreek2schrijf"
      shell: |
        if [ ! -f phrase-table.gz ]; then
          wget https://applejack.science.ru.nl/downloads/spreek2schrijf/phrase-table.gz || exit 1
        fi
        if [ ! -f allconversations.lm ]; then
          bunzip2 -k allconversations.lm.bz2
        fi
      args:
        chdir: "{{lm_prefix}}/src/spreek2schrijf/model"

