---
    - name: Updating base system (Pacman)
      become: true
      become_user: root
      pacman:
         update_cache: yes
         upgrade: yes
      when: (ansible_distribution == 'Arch') and root == True
