---
    - name: Updating base system (Arch)
      become: true
      become_user: root
      pacman:
         update_cache: yes
         upgrade: "{% if nosysupdate is not defined or nosysupdate == 0 %}no{% else %}yes{% endif %}"

    - name: installing common base packages (Arch)
      become: true
      become_user: root
      pacman:
        name: [pkgconf, git, mercurial, autoconf-archive, icu, libxml2, zlib, libtar, boost, boost-libs, nano, make, wget, curl, libexttextcat, perl, python, python-virtualenv, python-pip, zip, unzip, pcre, poppler, pandoc, hdf5]
        state: installed

      #############################################################
      # ANSIBLE installation so we can bootstrap ourselves
      ############################################################

    - when: locality == "global"
      block:
        - name: Install ansible
          become: true
          become_user: root
          pacman:
            name: "ansible"
            state: installed
