---
    - name: Updating base system (Homebrew)
      become: true
      become_user: root
      yum:
        name: "*"
        state: latest
      when: (ansible_distribution == 'MacOSX') and root == True
