---
    - name: Updating base system (Homebrew)
      homebrew:
        update_homebrew: yes
        upgrade_all: yes
      when: (ansible_distribution == 'MacOSX') and root == True


    - name: Installing common base packages (Homebrew)
      homebrew:
        name: "{{item}}"
        state: present
      with_items:
        - pkg-config
        - autoconf
        - automake
        - libtool
        - autoconf-archive
        - xml2
        - libxslt
        - icu4c
        - libtextcat
        - wget
        - ansible
      when: (nosysupdate is not defined or nosysupdate == false) and not prefer_local

    - name: Boost with Python 3
      command: brew install boost --with-python3 boost-python
      when: (nosysupdate is not defined or nosysupdate == false) and not prefer_local

