---
    - name: Updating base system (Homebrew)
      become: true
      become_user: root
      homebrew:
        update_homebrew: yes
        upgrade_all: yes
      when: (ansible_distribution == 'MacOSX') and root == True
