---

    - name: Checking whether virtualenv environment exists
      stat:
         path: "{{ local_prefix }}"
      changed_when: false
      register: virtualenv

    - when: virtualenv.stat.isdir is not defined or not virtualenv.stat.isdir
      block:
           - name: Creating bare virtualenv environment for LaMachine
             shell: "virtualenv --python=python3 {{ local_prefix }}"

    - name: Adapting activation script for virtualenv
      blockinfile:
        dest: "{{local_prefix}}/bin/activate"
        block: |
          export LD_LIBRARY_PATH={{local_prefix}}/lib/
        marker: '# {mark} LAMACHINE MANAGED BLOCK - lamachine environment'
        insertafter: EOF
        create: yes
        mode: u+rwx
