---

    - name: Checking whether virtualenv environment exists
      stat:
         path: "{{ local_prefix }}"
      changed_when: false
      register: virtualenv

    - when: virtualenv.stat.isdir is not defined or not virtualenv.stat.isdir
      block:
           - name: Creating bare virtualenv environment for LaMachine
             shell: "virtualenv {% if ansible_distribution|lower != 'centos' and ansible_distribution|lower != 'rhel' %}--always-copy{% endif %} --python={{ python_bin }} {{ local_prefix }}"

    - name: Adapting activation script for virtualenv
      blockinfile:
        dest: "{{local_prefix}}/bin/activate"
        block: |
          export LD_LIBRARY_PATH={{local_prefix}}/lib/
          for f in $VIRTUAL_ENV/bin/activate.d/*.sh; do
            if [ ! -z "$f" ]; then
                source $f
            fi
          done
        marker: '# {mark} LAMACHINE MANAGED BLOCK - lamachine environment'
        insertafter: EOF
        create: yes
        mode: u+rwx

    - name: Adding activate.d directory for extra activation scripts (local)
      file:
        path: "{{local_prefix}}/bin/activate.d"
        state: directory
      when: locality == "local"
