---

    - name: Checking whether virtualenv environment exists
      stat:
         path: "{{ local_prefix }}"
      changed_when: false
      register: virtualenv

    - when: virtualenv.stat.isdir is not defined or not virtualenv.stat.isdir
      block:
           - name: Creating bare virtualenv environment for LaMachine
             shell: "virtualenv --python=python3 {{ local_prefix }}"
