---
  - when: (ansible_distribution|lower == "macosx" and webservertype == "nginx")
    block:
      - name: Installing webserver (macOS)
        homebrew:
          name: "{{item}}"
          state: latest
        with_items: [nginx]

      - name: Link nginx from global prefix
        file:
          src: "/usr/local/etc/nginx"
          dest: "{{ lm_prefix }}/etc/nginx"
          state: link

      - name: Add nginx/conf.d directory
        become: "{{lm_become}}"
        become_user: root
        file:
            path: "{{ lm_prefix }}/etc/nginx/conf.d"
            state: directory
            owner: "{{unix_user}}"
            group: "{{web_group}}"
            mode: u+rwx,g+rwsx,a+rx

      - name: Patch for macOS so uwsgi installation can work
        file:
            src: "{{ lm_prefix}}/lib/python{{python_version.stdout}}/config-{{python_version.stdout}}-darwin"
            dest: "{{ lm_prefix}}/lib/python{{python_version.stdout}}/config-{{python_version.stdout}}"
            state: link
        ignore_errors: yes


      - name: Installing uwsgi (Homebrew)
        homebrew:
          name: uwsgi
          state: present
          install_options: "with-python"

  - when: root and locality=="global"
    block:

      - when: webservertype == "nginx"
        block:
          - name: Installing webserver globally (Debian/Ubuntu)
            become: true
            become_user: root
            apt:
              name: nginx
              state: latest
            when: (ansible_distribution|lower == "debian" or ansible_distribution|lower == "ubuntu" or ansible_distribution|lower == "linux mint")

          - name: Installing webserver globally (RedHat)
            become: true
            become_user: root
            yum:
              name: "{{item}}"
              state: latest
            with_items: [nginx]
            when: (ansible_distribution|lower == "redhat" or ansible_distribution|lower == "centos" or ansible_distribution|lower == "fedora" or ansible_distribution|lower == "rhel")

          - name: Installing webserver globally (Arch)
            become: true
            become_user: root
            pacman:
              name: nginx
              state: latest
            when: (ansible_distribution|lower == "archlinux")

      - name: Installing uwsgi globally (Debian/Ubuntu)
        become: true
        become_user: root
        apt:
          name: "{{item}}"
          state: latest
        with_items: [uwsgi-emperor, uwsgi, uwsgi-plugin-python3]
        when: (ansible_distribution|lower == "debian" or ansible_distribution|lower == "ubuntu" or ansible_distribution|lower == "linux mint")

      - name: Installing uwsgi globally (RedHat)
        become: true
        become_user: root
        pip:
          name: "uwsgi"
          state: latest
          executable: /usr/bin/pip3
        when: (ansible_distribution|lower == "redhat" or ansible_distribution|lower == "centos" or ansible_distribution|lower == "fedora" or ansible_distribution|lower == "rhel")


      - name: Installing uwsgi globally (Arch)
        become: true
        become_user: root
        pacman:
          name: "{{item}}"
          state: latest
        with_items: [uwsgi, uwsgi-plugin-python]
        when: (ansible_distribution|lower == "archlinux")


      - name: "Ensure {{web_group}} group exists"
        become: true
        become_user: root
        group:
          name: "{{web_group}}"
          state: present

      - name: "Ensure {{web_user}} user exists"
        become: true
        become_user: root
        user:
          name: "{{web_user}}"
          group: "{{web_group}}"
          createhome: no
          state: present

      - name: "Ensure {{unix_user}} user is also in {{web_group}} group"
        become: true
        become_user: root
        user:
          name: "{{unix_user}}"
          groups: "{{web_group}}"
          append: yes

      - name: Create webserver writable directories (global)
        become: "{{lm_become}}"
        become_user: root
        file:
            path: "{{ lm_prefix }}/{{item}}"
            state: directory
            owner: "{{unix_user}}"
            group: "{{web_group}}"
            mode: u+rwx,g+rwsx,a+rx
        with_items:
            - "var/log/uwsgi"
            - "var/log/nginx"
            - "var/www-data"
            - "var/www-data/tmp"

      - name: Link nginx from global prefix
        file:
          src: "/etc/nginx"
          dest: "{{ lm_prefix }}/etc/nginx"
          state: link
        when: ansible_distribution|lower != "macosx"

      - name: Link uwsgi-emperor from global prefix (debian)
        file:
          src: "/etc/uwsgi-emperor"
          dest: "{{ lm_prefix }}/etc/uwsgi-emperor"
          state: link
        when: (ansible_distribution|lower == "debian" or ansible_distribution|lower == "ubuntu" or ansible_distribution|lower == "linux mint")

      - name: Create webserver readable directories (global, non-debian)
        file:
            path: "{{ lm_prefix }}/{{item}}"
            state: directory
            owner: "{{unix_user}}"
            mode: u+rwx,a+rx
        with_items:
            - "etc/uwsgi-emperor"
            - "etc/uwsgi-emperor/vassals"
        when: not (ansible_distribution|lower == "debian" or ansible_distribution|lower == "ubuntu" or ansible_distribution|lower == "linux mint")

  - when: locality=="local"
    block:

      - name: Create writable directories for uwsgi (local)
        file:
            path: "{{ lm_prefix }}/{{item}}"
            state: directory
            owner: "{{unix_user}}"
            mode: u+rwx,a+rx
        with_items:
            - "var/log/uwsgi"
            - "etc/uwsgi-emperor"
            - "etc/uwsgi-emperor/vassals"

      - when: webservertype == "nginx"
        block:
          - name: "Finding nginx"
            shell: which nginx
            register: nginx
            environment:
                PATH: "{{local_prefix}}/bin:/usr/sbin:{{ansible_env.PATH}}"
            failed_when: nginx.rc == 127

          - name: Create webserver writable directories (local)
            file:
                path: "{{ lm_prefix }}/{{item}}"
                state: directory
                owner: "{{unix_user}}"
                mode: u+rwx,a+rx
            with_items:
                - "var/log/nginx"
                - "var/www-data"
                - "var/www-data/tmp"
                - "etc/nginx"
                - "etc/nginx/conf.d"

          - when: ansible_distribution|lower != "macosx" and (nginx.rc != 0 or (force is defined and force))
            block:
              - block:
                  - name: Obtaining local nginx webserver from source
                    hg:
                      repo: https://hg.nginx.org/nginx
                      dest: "{{source_path}}/nginx"
                      force: "yes"
                rescue:
                  - name: Obtaining local nginx webserver from source (2nd attempt, insecure fallback)
                    shell: hg clone --insecure https://hg.nginx.org/nginx
                    args:
                      chdir: "{{source_path}}"

              - name: "Compiling and installing local nginx webserver"
                shell: "auto/configure --prefix={{lm_prefix}} && make && make install"
                args:
                    chdir: "{{ source_path }}/nginx"
                environment: "{{lm_env}}"

              - name: Linking to nginx binary
                file:
                  src: "{{ lm_prefix}}/sbin/nginx"
                  dest: "{{ lm_prefix }}/bin/nginx"
                  state: link

              - name: Copying extra configuration
                copy:
                  src: "{{source_path}}/nginx/conf/{{item}}"
                  dest: "{{lm_prefix}}/etc/nginx/{{item}}"
                with_items:
                  - "mime.types"
                  - "uwsgi_params"
                ignore_errors: yes


      - name: Installing uwsgi locally
        pip:
          name: "uwsgi"
          state: latest
          executable: "{{lm_prefix}}/bin/pip"
        when: ansible_distribution|lower != "macosx"

  - name: Install webserver configuration
    become: "{{lm_become}}"
    become_user: root
    template:
      src: "{{item}}"
      dest: "{{lm_prefix}}/etc/nginx/{{item}}"
      force: yes
      owner: "{{unix_user}}"
      group: "{{unix_group}}"
    with_items:
      - nginx.conf
      - mime.types
      - uwsgi_params
    when: webservertype == "nginx"

  - name: Adding webserver start script
    become: "{{lm_become}}"
    become_user: root
    template:
      src: lamachine-start-webserver.sh
      dest: "{{lm_prefix}}/bin/lamachine-start-webserver"
      owner: "{{unix_user}}"
      group: "{{unix_group}}"
      mode: u+rwx,g+rwx,o-rwx

  - name: Adding webserver stop script
    become: "{{lm_become}}"
    become_user: root
    template:
      src: lamachine-stop-webserver.sh
      dest: "{{lm_prefix}}/bin/lamachine-stop-webserver"
      owner: "{{unix_user}}"
      group: "{{unix_group}}"
      mode: u+rwx,g+rwx,o-rwx

  - name: Install uwsgi-emperor configuration
    become: "{{lm_become}}"
    become_user: root
    template:
      src: emperor.ini
      dest: "{{lm_prefix}}/etc/uwsgi-emperor/emperor.ini"
      force: yes
      backup: yes
      owner: "{{unix_user}}"
      group: "{{unix_group}}"
      mode: u+rwx,g+rwx,o-rwx

  - name: Create document root
    become: "{{lm_become}}"
    become_user: root
    file:
        path: "{{ lm_prefix }}/var/www-data/docroot"
        state: directory
        owner: "{{unix_user}}"
        mode: u+rwx,a+rx

  - name: Copy document root
    become: "{{lm_become}}"
    become_user: root
    copy:
      src: "{{item}}"
      dest: "{{ lm_prefix}}/var/www-data/docroot"
    with_fileglob:
      - "{{lm_path}}/webserver/docroot/*"
