---

    - name: Output warning
      debug:
        msg: "t2t requires access to a private gitlab server and will fail if you do not have access (based on ssh keypairs)"

    - name: Installing t2t python package
      include_role:
        name: lamachine-python-install
      vars:
        package:
          name: "t2t"
          git_url: "git@gitlab.science.ru.nl:ltenbosch/t2t.git"

    - name: Register webservice
      include_role:
          name: lamachine-register
      vars:
        update: "t2t"
        package:
           pip: "t2t"
        allow_failure: yes #in case the app is not installed
        metadata: #add entrypoint metadata to registry
            identifier: "t2t"
            entryPoints:
              - { "@type": "EntryPoint",  urlTemplate: "{{lm_base_url}}/t2t", interfaceType: "WUI" }
              - { "@type": "EntryPoint",  urlTemplate: "{{lm_base_url}}/t2t", interfaceType: "REST", specification: "{{lm_base_url}}/t2t/info" }

    - name: Installing web service
      include_role:
        name: lamachine-web-install
      vars:
        service:
          nginx: t2t
          clam: t2t
          uwsgi: t2t

    - name: Link Python package installation in opt/
      include_role:
        name: lamachine-python-link
      with_items:
        - t2t
