---
  - name: Obtaining Labirinto
    include_role:
      name: lamachine-git
    vars:
      package:
        user: proycon
        repo: labirinto

  - name: Installing Labirinto dependencies
    shell: npm install
    args:
      chdir: "{{ source_path }}/labirinto"

  - name: Building Labirinto
    shell: npm run build
    args:
      chdir: "{{ source_path }}/labirinto"
