---
  - name: Obtaining Labirinto
    include_role:
      name: lamachine-git
    vars:
      package:
        user: proycon
        repo: labirinto

  - name: Installing Labirinto dependencies
    shell: npm install
    args:
      chdir: "{{ source_path }}/labirinto"

  - name: Install webserver configuration
    become: "{{lm_become}}"
    become_user: root
    template:
      src: "nginx/labirinto.conf"
      dest: "{{lm_prefix}}/etc/nginx/conf.d/labirinto.conf"
      force: yes
      owner: "{{unix_user}}"
      group: "{{unix_group}}"
    when: webservertype == "nginx"

  - name: Copying build file
    template:
      src: "prod.env.js"
      dest: "{{ source_path }}/labirinto/config/prod.env.js"
      force: yes
      owner: "{{unix_user}}"
      group: "{{unix_group}}"

  - name: Building Labirinto
    shell: npm run build
    args:
      chdir: "{{ source_path }}/labirinto"

  - name: Deploying to document root
    become: "{{lm_become}}"
    become_user: root
    shell: "cp -r {{ source_path }}/labirinto/dist/* {{lm_prefix}}/var/www-data/docroot/"
