---
  - name: Installing Alex-ASR
    include_role:
      name: lamachine-python-install
    vars:
      package:
         github_user: "UFAL-DSG"
         github_repo: "alex-asr"
         #pip: "alex_asr"
